Repository CitiesSkylinesMods/TMPE, pull requests merged in 2019-02, with the labels that each got.

#31 Improved train restriction icons, for #17
  TLM/TLM/Resources/cargotrain_allowed.png
  TLM/TLM/Resources/cargotrain_forbidden.png
  TLM/TLM/Resources/passengertrain_allowed.png
  TLM/TLM/Resources/passengertrain_forbidden.png
  TLM/TLM/Resources/template/allowed.png
  TLM/TLM/Resources/template/disallowed.png
Labels: accessibility improvements

#37 Infosign icons for trains, fixes #17
  TLM/TLM/Resources/cargotrain_infosign.png
  TLM/TLM/Resources/passengertrain_infosign.png
Labels: accessibility improvements

#25 Turn On Red (Previously Right On Red)
  TLM/TLM/Geometry/Impl/SegmentGeometry.cs
  TLM/TLM/Manager/IJunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Resources/lang.txt
  TLM/TLM/Resources/lang_de.txt
  TLM/TLM/Resources/lang_es.txt
  TLM/TLM/Resources/lang_fr.txt
  TLM/TLM/Resources/lang_it.txt
  TLM/TLM/Resources/lang_ja.txt
  TLM/TLM/Resources/lang_ko.txt
  TLM/TLM/Resources/lang_nl.txt
  TLM/TLM/Resources/lang_pl.txt
  TLM/TLM/Resources/lang_pt.txt
  TLM/TLM/Resources/lang_ru.txt
  TLM/TLM/Resources/lang_zh-tw.txt
  TLM/TLM/Resources/lang_zh.txt
  TLM/TLM/Resources/left_on_red_allowed.png
  TLM/TLM/Resources/left_on_red_forbidden.png
  TLM/TLM/Resources/right_on_red_allowed.png
  TLM/TLM/Resources/right_on_red_forbidden.png
  TLM/TLM/State/ConfigData/Debug.cs
  TLM/TLM/State/Configuration.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Traffic/Data/SegmentEndFlags.cs
  TLM/TLM/Traffic/Data/SegmentFlags.cs
  TLM/TLM/UI/SubTools/JunctionRestrictionsTool.cs
  TLM/TLM/UI/TextureResources.cs
  TLM/TLM/UI/UIMainMenuButton.cs
Labels: feature

#93 Added incompatible_mods.txt - updates #91
  TLM/TLM/Resources/incompatible_mods.txt
Labels: enhancement, usability

#94 Update incompaatible_mods.txt - updates #91
  TLM/TLM/Resources/incompatible_mods.txt
Labels: enhancement

#98 Edit incompatible_mods.txt - updates #91
  TLM/TLM/Resources/incompatible_mods.txt
Labels: enhancement

#95 Esc key handler
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/UIBase.cs
Labels: bug, confirmed

#97 Project building instructions
  TLM/BUILDING_INSTRUCTIONS.md
  TLM/PR_REVIEW_INSTRUCTIONS.md
  TLM/TLM/TLM.csproj
Labels: docs

#105 Moved changelog to its own file
  CHANGELOG.md
  README.md
Labels: docs

#106 Incompatible mods detection
  TLM/TLM/Resources/incompatible_mods.txt
  TLM/TLM/TLM.csproj
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/UI/IncompatibleModsPanel.cs
  TLM/TLM/Util/ModCompatibilityHelper.cs
  TLM/TLM/Util/ModsCompatibilityChecker.cs
Labels: enhancement, usability

#109 Update CHANGELOG.md
  CHANGELOG.md
Labels: docs

#108 Turn on red toggle fix
  TLM/TLM/Manager/IJunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Traffic/Data/SegmentEndFlags.cs
  TLM/TLM/Traffic/Data/SegmentFlags.cs
  TLM/TLM/UI/SubTools/JunctionRestrictionsTool.cs
Labels: bug, confirmed

#110 Update README.md
  README.md
Labels: docs

#115 Incompat mods
  TLM/TLM/Resources/incompatible_mods.txt
Labels: external, usability

#116 Update README.md
  README.md
Labels: docs
