Repository CitiesSkylinesMods/TMPE, pull requests merged in 2019-08, with the labels that each got.

#475 #438 Speedlimit refactor
  TLM/TLM/Constants.cs
  TLM/TLM/Custom/AI/CustomCarAI.cs
  TLM/TLM/Custom/AI/CustomHumanAI.cs
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/Custom/PathFinding/CustomPathManager.cs
  TLM/TLM/Manager/AbstractGeometryObservingManager.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/CustomSegmentLightsManager.cs
  TLM/TLM/Manager/Impl/ExtBuildingManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenManager.cs
  TLM/TLM/Manager/Impl/ExtNodeManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentManager.cs
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/GeometryManager.cs
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/LaneArrowManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/ParkingRestrictionsManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/Manager/Impl/TrafficMeasurementManager.cs
  TLM/TLM/Manager/Impl/TrafficPriorityManager.cs
  TLM/TLM/Manager/Impl/TurnOnRedManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/State/ConfigData/DynamicLaneSelection.cs
  TLM/TLM/State/ConfigData/Main.cs
  TLM/TLM/State/Configuration.cs
  TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Traffic/Data/SpeedLimit.cs
  TLM/TLM/TrafficLight/Impl/CustomSegmentLight.cs
  TLM/TLM/TrafficLight/Impl/CustomSegmentLights.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLightsStep.cs
  TLM/TLM/UI/SubTools/ManualTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/PrioritySignsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/MphSignStyle.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedUnit.cs
  TLM/TLM/UI/SubTools/TimedTrafficLightsTool.cs
  TLM/TLM/UI/Textures/JunctionUITextures.cs
  TLM/TLM/UI/Textures/SpeedLimitTextures.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/FloatUtil.cs
  TLM/TLM/Util/SegmentTraverser.cs
  TLM/TMPE.API/TMPE.API.csproj
  TLM/TMPE.API/Traffic/ApiConstants.cs
  TLM/TMPE.API/Traffic/Data/SpeedValue.cs
Labels: code-cleanup, technical

#476 TinyDictionaryUnitTest - code cleanup
  TLM/TMPE.UnitTest/Util/TinyDictionaryUnitTest.cs
Labels: code-cleanup, technical

#478 Cargo Info mod is incompatible
  TLM/TLM/Resources/incompatible_mods.txt
Labels: EXTERNAL, usability

#492 Add Hungarian language
  TLM/TLM/Resources/lang_hu.txt
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/Translation.cs
Labels: Localisation, UI

#486 Updated issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/translation-update.md
Labels: meta

#483 Fix regression: Train icons
  TLM/TLM/Resources/cargotrain_allowed.png
  TLM/TLM/Resources/cargotrain_forbidden.png
  TLM/TLM/Resources/cargotrain_infosign.png
  TLM/TLM/Resources/passengertrain_allowed.png
  TLM/TLM/Resources/passengertrain_forbidden.png
  TLM/TLM/Resources/passengertrain_infosign.png
Labels: Accessibility, Overlays, UI, VEHICLE RESTRICTIONS

#513 Remove decorative and non-vehicle networks from speed limits manager.
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/State/ConfigData/DebugSettings.cs
Labels: 11 ALPHA, SPEED LIMITS, Settings, UI, code cleanup, under-review

#474 Docs folder + updated docs
  README.md
  TLM/ATTACHING_DEBUGGER.md
  TLM/BUILDING_INSTRUCTIONS.md
  TLM/PR_REVIEW_INSTRUCTIONS.md
  docs/ATTACHING_DEBUGGER.md
  docs/BUILDING_INSTRUCTIONS.md
  docs/LOGGING.md
  docs/PR_REVIEW_INSTRUCTIONS.md
Labels: docs, meta, under-review
