Repository CitiesSkylinesMods/TMPE, pull requests merged in 2019-04, with the labels that each got.

#258 Update lang_ja.txt
  TLM/TLM/Resources/lang_ja.txt
Labels: localisation, usability

#274 Update README
  README.md
Labels: meta

#266 Fixed options indentation
  TLM/TLM/State/Options.cs
Labels: LABS, STABLE, bug, confirmed, waiting

#290 Update incompatible_mods.txt
  TLM/TLM/Resources/incompatible_mods.txt
Labels: EXTERNAL, LABS, usability

#285 Timed traffic lights step - confirm before delete
  TLM/TLM/Resources/lang_ja.txt
  TLM/TLM/UI/SubTools/TimedTrafficLightsTool.cs
Labels: LABS, enhancement, usability

#286 #264: disable incompatible mod warning
  TLM/TLM/Resources/lang.txt
  TLM/TLM/Resources/lang_de.txt
  TLM/TLM/Resources/lang_es.txt
  TLM/TLM/Resources/lang_fr.txt
  TLM/TLM/Resources/lang_it.txt
  TLM/TLM/Resources/lang_ja.txt
  TLM/TLM/Resources/lang_ko.txt
  TLM/TLM/Resources/lang_nl.txt
  TLM/TLM/Resources/lang_pl.txt
  TLM/TLM/Resources/lang_pt.txt
  TLM/TLM/Resources/lang_ru.txt
  TLM/TLM/Resources/lang_template.txt
  TLM/TLM/Resources/lang_zh-tw.txt
  TLM/TLM/Resources/lang_zh.txt
  TLM/TLM/State/ConfigData/Main.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/UI/IncompatibleModsPanel.cs
  TLM/TLM/Util/ModsCompatibilityChecker.cs
Labels: LABS, enhancement, usability

#291 Updated changelogs for 10.19 release
  CHANGELOG.md
  README.md
Labels: docs, meta
