Repository CitiesSkylinesMods/TMPE, pull requests merged in 2019-03, with the labels that each got.

#121 Turn-on-red feature: cleaned up code and translations
  TLM/TLM/Geometry/Impl/SegmentGeometry.cs
  TLM/TLM/LoadingExtension.cs
  TLM/TLM/Manager/AbstractCustomManager.cs
  TLM/TLM/Manager/IGeometryManager.cs
  TLM/TLM/Manager/IJunctionRestrictionsManager.cs
  TLM/TLM/Manager/ILaneConnectionManager.cs
  TLM/TLM/Manager/IManagerFactory.cs
  TLM/TLM/Manager/ITurnOnRedManager.cs
  TLM/TLM/Manager/Impl/GeometryManager.cs
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/ManagerFactory.cs
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/Manager/Impl/TrafficLightManager.cs
  TLM/TLM/Manager/Impl/TrafficPriorityManager.cs
  TLM/TLM/Manager/Impl/TurnOnRedManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Resources/lang.txt
  TLM/TLM/Resources/lang_de.txt
  TLM/TLM/Resources/lang_es.txt
  TLM/TLM/Resources/lang_fr.txt
  TLM/TLM/Resources/lang_it.txt
  TLM/TLM/Resources/lang_ja.txt
  TLM/TLM/Resources/lang_ko.txt
  TLM/TLM/Resources/lang_nl.txt
  TLM/TLM/Resources/lang_pl.txt
  TLM/TLM/Resources/lang_pt.txt
  TLM/TLM/Resources/lang_ru.txt
  TLM/TLM/Resources/lang_template.txt
  TLM/TLM/Resources/lang_zh-tw.txt
  TLM/TLM/Resources/lang_zh.txt
  TLM/TLM/State/ConfigData/Debug.cs
  TLM/TLM/State/ConfigData/PriorityRules.cs
  TLM/TLM/State/Configuration.cs
  TLM/TLM/State/GlobalConfig.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Traffic/Data/SegmentEndFlags.cs
  TLM/TLM/Traffic/Data/SegmentFlags.cs
  TLM/TLM/Traffic/Data/TurnOnRedSegments.cs
  TLM/TLM/Traffic/Impl/SegmentEnd.cs
  TLM/TLM/UI/SubTools/JunctionRestrictionsTool.cs
Labels: enhancement

#117 Update incompatible_mods.txt
  TLM/TLM/Resources/incompatible_mods.txt
Labels: usability

#252 #248: #53: Disable turn-on-red behavior for non-road vehicles
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
Labels: enhancement

#255 Update incompatible_mods.txt
  TLM/TLM/Resources/incompatible_mods.txt
Labels: EXTERNAL, enhancement

#251 #245: Improved outside connection detection
  TLM/TLM/Custom/AI/CustomCarAI.cs
  TLM/TLM/Custom/AI/CustomCitizenAI.cs
  TLM/TLM/Custom/AI/CustomHumanAI.cs
  TLM/TLM/Custom/AI/CustomPassengerCarAI.cs
  TLM/TLM/Custom/AI/CustomResidentAI.cs
  TLM/TLM/Custom/AI/CustomTouristAI.cs
  TLM/TLM/Manager/IExtCitizenInstanceManager.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/State/ConfigData/Debug.cs
  TLM/TLM/Traffic/Data/ExtCitizenInstance.cs
Labels: enhancement

#253 v10.18: Readme, changelog
  CHANGELOG.md
  README.md
  TLM/TLM/TrafficManagerMod.cs
Labels: docs
