Repository CitiesSkylinesMods/TMPE, pull requests merged in 2019-05, with the labels that each got.

#303 Add Support Notice to README
  README.md
Labels: high priority, meta

#294 Update lang_ko.txt
  TLM/TLM/Resources/lang_ko.txt
Labels: UI, localisation

#311 Update lang_fr.txt
  TLM/TLM/Resources/lang_fr.txt
Labels: UI, localisation, usability

#323 Update release notes & changelog
  CHANGELOG.md
  README.md
Labels: localisation, meta

#328 Updated lang_ru - Fixes #327
  TLM/TLM/Resources/lang_ru.txt
Labels: UI, localisation, usability

#332 Update incompatible_mods.txt - Fixes #331
  TLM/TLM/Resources/incompatible_mods.txt
Labels: EXTERNAL, technical

#272 Add Issue Template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/translation-update.md
Labels: meta

#334 Randomized DLS
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Manager/Impl/VehicleStateManager.cs
  TLM/TLM/Resources/lang.txt
  TLM/TLM/Resources/lang_de.txt
  TLM/TLM/Resources/lang_es.txt
  TLM/TLM/Resources/lang_fr.txt
  TLM/TLM/Resources/lang_it.txt
  TLM/TLM/Resources/lang_ja.txt
  TLM/TLM/Resources/lang_ko.txt
  TLM/TLM/Resources/lang_nl.txt
  TLM/TLM/Resources/lang_pl.txt
  TLM/TLM/Resources/lang_pt.txt
  TLM/TLM/Resources/lang_ru.txt
  TLM/TLM/Resources/lang_template.txt
  TLM/TLM/Resources/lang_zh-tw.txt
  TLM/TLM/Resources/lang_zh.txt
  TLM/TLM/State/ConfigData/DynamicLaneSelection.cs
  TLM/TLM/State/ConfigData/Gameplay.cs
  TLM/TLM/State/GlobalConfig.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Traffic/Data/VehicleState.cs
  TLM/TLM/Util/MathUtil.cs
Labels: enhancement, usability

#338 Mail Trucks Ignore Lane Arrows
  TLM/TLM/Custom/AI/CustomPostVanAI.cs
  TLM/TLM/Custom/PathFinding/CustomPathFind2.cs
  TLM/TLM/LoadingExtension.cs
  TLM/TLM/TLM.csproj
Labels: enhancement, technical
