Repository CitiesSkylinesMods/TMPE, pull requests merged in 2019-11, with the labels that each got.

#536 Path-find stats & Benchmark profile fix
  TLM/CSUtil.Commons/CSUtil.Commons.csproj
  TLM/TLM/Resources/Translations/AI_Car.csv
  TLM/TLM/Resources/Translations/AI_Citizen.csv
  TLM/TLM/Resources/Translations/LaneRouting.csv
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/Resources/Translations/ModConflicts.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
  TLM/TLM/Resources/Translations/Tutorials.csv
  TLM/TLM/Resources/Translations/VehicleRestrictions.csv
  TLM/TLM/State/OptionsTabs/OptionsMaintenanceTab.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/UI/MainMenu/MainMenuPanel.cs
  TLM/TLM/UI/MainMenu/StatsLabel.cs
  TLM/TMPE.sln
Labels: 11 ALPHA, Localisation, code cleanup, enhancement, performance

#545 Bugfix - manual traffic lights tool index out of range
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
  TLM/TLM/UI/SubTools/ManualTrafficLightsTool.cs
Labels: 11 ALPHA, BUG, TRAFFIC LIGHTS

#538 shortcuts for separating turning lanes
  TLM/TLM/Manager/Impl/LaneArrowManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/UI/MainMenu/LaneArrowsButton.cs
  TLM/TLM/UI/SubTools/LaneArrowTool.cs
Labels: 11 ALPHA, LANE ROUTING, Usability, feature

#550 IterateNodeSegments sometimes does not work. Fixes #549
  TLM/TMPE.CitiesGameBridge/Service/NetService.cs
Labels: BUG, confirmed

#570 Null reference OnEnable - hotfix
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: BUG, confirmed

#572 Turkish and Ukrainian language support
  TLM/TLM/Resources/Translations/AI_Car.csv
  TLM/TLM/Resources/Translations/AI_Citizen.csv
  TLM/TLM/Resources/Translations/JunctionRestrictions.csv
  TLM/TLM/Resources/Translations/LaneRouting.csv
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/Resources/Translations/ModConflicts.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/ParkingRestrictions.csv
  TLM/TLM/Resources/Translations/PrioritySigns.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
  TLM/TLM/Resources/Translations/Tutorials.csv
  TLM/TLM/Resources/Translations/VehicleRestrictions.csv
  TLM/TLM/UI/Localization/Translation.cs
Labels: Localisation

#580 Disambiguate `LeftHandDrive` to `TrafficDrivesOnLeft`
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/LaneArrowManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/TrafficPriorityManager.cs
  TLM/TLM/Manager/Impl/TurnOnRedManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/TrafficLight/Impl/CustomSegmentLight.cs
  TLM/TLM/TrafficLight/Impl/CustomSegmentLights.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLightsStep.cs
  TLM/TLM/UI/SubTools/JunctionRestrictionsTool.cs
  TLM/TMPE.CitiesGameBridge/Service/SimulationService.cs
  TLM/TMPE.GenericGameBridge/Service/ISimulationService.cs
Labels: Annoyance, JUNCTION RESTRICTIONS, LANE ROUTING, TRAFFIC LIGHTS, adjustments required, code cleanup, technical
