Repository CitiesSkylinesMods/TMPE, pull requests merged in 2019-12, with the labels that each got.

#579 Ensure a valid langauge is always used
  TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/UI/Localization/Translation.cs
Labels: 11 ALPHA, Localisation, technical

#564 Half overlay
  TLM/TLM/Manager/Impl/LaneArrowManager.cs
  TLM/TLM/UI/SubTool.cs
  TLM/TLM/UI/SubTools/LaneArrowTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: DO NOT MERGE YET, Overlays, UI, Usability

#589 Fix CSV multi-line translation
  .gitattributes
  TLM/TLM/UI/Localization/LookupTable.cs
  TLM/TMPE.UnitTest/TMPE.UnitTest.csproj
  TLM/TMPE.UnitTest/Translation/CsvParser.cs
  TLM/TMPE.UnitTest/Translation/TestFiles/MultilineTestBlock_CRLF.test
  TLM/TMPE.UnitTest/Translation/TestFiles/MultilineTestBlock_LF.test
  TLM/TMPE.UnitTest/Translation/TestFiles/TestBlock_CRLF.test
  TLM/TMPE.UnitTest/Translation/TestFiles/TestBlock_LF.test
Labels: 11 ALPHA, DO NOT MERGE YET, Localisation

#596 Added a readme to translations folder
  TLM/TLM/Resources/Translations/README.md
Labels: docs, meta

#554 default Timed traffic light
  TLM/CSUtil.Commons/ArrowDirection.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/MainMenu/TimedTrafficLightsButton.cs
  TLM/TLM/UI/SubTools/TimedTrafficLightsTool.cs
  TLM/TLM/Util/AutoTimedTrafficLights.cs
Labels: TRAFFIC LIGHTS, enhancement

#599 Translations update
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
Labels: 11 ALPHA, Localisation
