Repository CitiesSkylinesMods/TMPE, pull requests merged in 2019-10, with the labels that each got.

#529 Fix #509 Main menu Despawning text
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/Resources/Translations/ModConflicts.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
  TLM/TLM/Resources/Translations/Tutorials.csv
  TLM/TLM/State/Keybinds/Keybind.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/UI/MainMenu/DespawnButton.cs
Labels: Localisation

#534 Game language detection fix - modded language
  TLM/TLM/UI/Localization/Translation.cs
Labels: 11 ALPHA, COMPATIBILITY, EXTERNAL, Localisation

#535 Function to Disable & Remove Traffic Lights
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/Manager/Impl/TrafficLightManager.cs
  TLM/TLM/Patch/_RoadBaseAI/UpdateNodePatch.cs
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/Resources/Translations/ModConflicts.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
  TLM/TLM/Resources/Translations/VehicleRestrictions.csv
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/OptionsMaintenanceTab.cs
  TLM/TLM/State/OptionsTabs/OptionsVehicleRestrictionsTab.cs
  TLM/TLM/TLM.csproj
  TLM/TMPE.API/Manager/ITrafficLightManager.cs
Labels: 11 ALPHA, TRAFFIC LIGHTS, UI, Usability, enhancement, feature
