Repository CitiesSkylinesMods/TMPE, pull requests merged in 2019-07, with the labels that each got.

#400 Exclude self from offline TMPE mod check
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/Util/ModsCompatibilityChecker.cs
Labels: technical, usability

#403 Update mod and game version
  TLM/TLM/TrafficManagerMod.cs
Labels: UI, high priority, technical

#382 Keyboard Shortcuts for TM:PE
  .gitignore
  TLM/TLM/Resources/lang.txt
  TLM/TLM/Resources/lang_de.txt
  TLM/TLM/Resources/lang_es.txt
  TLM/TLM/Resources/lang_fr.txt
  TLM/TLM/Resources/lang_it.txt
  TLM/TLM/Resources/lang_ja.txt
  TLM/TLM/Resources/lang_ko.txt
  TLM/TLM/Resources/lang_nl.txt
  TLM/TLM/Resources/lang_pl.txt
  TLM/TLM/Resources/lang_pt.txt
  TLM/TLM/Resources/lang_ru.txt
  TLM/TLM/Resources/lang_template.txt
  TLM/TLM/Resources/lang_zh-tw.txt
  TLM/TLM/Resources/lang_zh.txt
  TLM/TLM/State/Keybinds/Keybind.cs
  TLM/TLM/State/Keybinds/KeybindSetting.cs
  TLM/TLM/State/Keybinds/KeybindSettingsBase.cs
  TLM/TLM/State/Keybinds/KeybindSettingsPage.cs
  TLM/TLM/State/Keybinds/KeybindUI.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/UI/LinearSpriteButton.cs
  TLM/TLM/UI/MainMenu/ClearTrafficButton.cs
  TLM/TLM/UI/MainMenu/DespawnButton.cs
  TLM/TLM/UI/MainMenu/JunctionRestrictionsButton.cs
  TLM/TLM/UI/MainMenu/LaneArrowsButton.cs
  TLM/TLM/UI/MainMenu/LaneConnectorButton.cs
  TLM/TLM/UI/MainMenu/MainMenuPanel.cs
  TLM/TLM/UI/MainMenu/ManualTrafficLightsButton.cs
  TLM/TLM/UI/MainMenu/MenuButton.cs
  TLM/TLM/UI/MainMenu/MenuToolModeButton.cs
  TLM/TLM/UI/MainMenu/ParkingRestrictionsButton.cs
  TLM/TLM/UI/MainMenu/PrioritySignsButton.cs
  TLM/TLM/UI/MainMenu/SpeedLimitsButton.cs
  TLM/TLM/UI/MainMenu/TimedTrafficLightsButton.cs
  TLM/TLM/UI/MainMenu/ToggleTrafficLightsButton.cs
  TLM/TLM/UI/MainMenu/VehicleRestrictionsButton.cs
  TLM/TLM/UI/MainMenu/VersionLabel.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/ToolMode.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/UI/UIBase.cs
  TLM/TLM/UI/UIMainMenuButton.cs
Labels: LABS, STABLE, UI, accessibility, feature, localisation

#396 Update README for 10.21 Release
  CHANGELOG.md
  README.md
Labels: docs, meta

#404 Blur position and zOrder fix
  TLM/TLM/UI/IncompatibleModsPanel.cs
Labels: LABS, STABLE, UI, bug

#405 Added release date to changelogs
  CHANGELOG.md
  README.md
Labels: meta

#413 Only perform logging in DEBUG builds
  TLM/TLM/UI/TextureResources.cs
Labels: LABS, problem, technical

#412 Refactor main changelog
  CHANGELOG.md
Labels: docs, meta

#414 Version 10.21.1 hotfix
  CHANGELOG.md
  README.md
  TLM/TLM/TrafficManagerMod.cs
Labels: LABS, docs

#417 Update lang_zh.txt
  TLM/TLM/Resources/lang_zh.txt
Labels: localisation

#422 Changelog - Added Traffic++ history
  CHANGELOG.md
Labels: docs

#443 Various mod checker tweaks
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/Util/ModsCompatibilityChecker.cs
Labels: code-cleanup, technical

#453 Update lang_fr.txt (thanks mjm92150)
  TLM/TLM/Resources/lang_fr.txt
Labels: UI, localisation

#455 Make it impossible to use TRACE option without DEBUG
  TLM/CSUtil.Commons/CSUtil.Commons.csproj
  TLM/CSUtil.Commons/Log.cs
Labels: code-cleanup, technical

#456 TMPE.API Release LABS build config fix
  TLM/TMPE.sln
Labels: 11 ALPHA, technical

#458 Show full mod name in mod checker title bar
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/UI/IncompatibleModsPanel.cs
Labels: UI, usability

#459 Parking restriction fix
  TLM/TLM/Custom/AI/CustomPassengerCarAI.cs
Labels: 11 ALPHA, bug, confirmed

#461 Change `static` to `const`
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/UI/MainMenu/VersionLabel.cs
Labels: code-cleanup

#463 Prevent usage of 'in' with non-readonly structs by a compiler error
  TLM/CSUtil.Commons/CSUtil.Commons.csproj
  TLM/CSUtil.Commons/packages.config
  TLM/TLM/TLM.csproj
  TLM/TLM/packages.config
  TLM/TMPE.CitiesGameBridge/TMPE.CitiesGameBridge.csproj
  TLM/TMPE.CitiesGameBridge/packages.config
  TLM/TMPE.GenericGameBridge/TMPE.GenericGameBridge.csproj
  TLM/TMPE.GenericGameBridge/packages.config
  TLM/TMPE.TestGameBridge/TMPE.TestGameBridge.csproj
  TLM/TMPE.TestGameBridge/packages.config
  TLM/TMPE.UnitTest/TMPE.UnitTest.csproj
  TLM/TMPE.UnitTest/packages.config
  TLM/TMPE.ruleset
Labels: code-cleanup, performance, technical

#473 Eliminate vehicle pause before entering junction if has right of way
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
Labels: 11 ALPHA
