Repository CitiesSkylinesMods/TMPE, pull requests merged in 2019-06, with the labels that each got.

#358 Minor fixes: Saving/Loading junction restrictions, UI overlay, Reset stuck cims
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/State/Options.cs
Labels: LABS, STABLE

#374 Remove TMPE.GlobalConfigGenerator project
  TLM/TMPE.GlobalConfigGenerator/App.config
  TLM/TMPE.GlobalConfigGenerator/Generator.cs
  TLM/TMPE.GlobalConfigGenerator/Properties/AssemblyInfo.cs
  TLM/TMPE.GlobalConfigGenerator/TMPE.GlobalConfigGenerator.csproj
  TLM/TMPE.GlobalConfigGenerator/packages.config
  TLM/TMPE.sln
Labels: code-cleanup, technical

#375 Update lang_zh.txt
  TLM/TLM/Resources/lang_zh.txt
Labels: UI, localisation, usability

#359 Parking AI loop
  TLM/TLM/Custom/AI/CustomCitizenAI.cs
  TLM/TLM/Custom/AI/CustomPassengerCarAI.cs
  TLM/TLM/Custom/PathFinding/CustomPathFind2.cs
  TLM/TLM/Custom/PathFinding/CustomPathManager.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Traffic/Data/ExtCitizenInstance.cs
Labels: LABS, STABLE

#355 No lane changes at toll boothes
  TLM/TLM/Custom/AI/CustomVehicleAI.cs
  TLM/TLM/Manager/IVehicleBehaviorManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
Labels: LABS, STABLE

#362 Use Actual Maximum Vehicle Count
  TLM/TLM/Custom/Data/CustomVehicle.cs
  TLM/TLM/Custom/Manager/CustomVehicleManager.cs
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/Manager/Impl/VehicleStateManager.cs
  TLM/TMPE.CitiesGameBridge/Service/VehicleService.cs
  TLM/TMPE.GenericGameBridge/Service/IVehicleService.cs
Labels: EXTERNAL, enhancement, technical

#392 Undo the dreadful tab indent in .editorconfig
  TLM/.editorconfig
Labels: technical

#395 .gitignore entire `.vs/` folder
  .gitignore
  TLM/.vs/config/applicationhost.config
Labels: code-cleanup, meta

#398 Explicitly Set C# Version to Latest
  TLM/CSUtil.Commons/CSUtil.Commons.csproj
  TLM/TLM/TLM.csproj
  TLM/TMPE.CitiesGameBridge/TMPE.CitiesGameBridge.csproj
  TLM/TMPE.GenericGameBridge/TMPE.GenericGameBridge.csproj
  TLM/TMPE.TestGameBridge/TMPE.TestGameBridge.csproj
  TLM/TMPE.UnitTest/TMPE.UnitTest.csproj
Labels: technical

#333 Differentiate Labs and Stable & Avoid Multiple Subscriptions
  TLM/TLM/Resources/lang.txt
  TLM/TLM/Resources/lang_de.txt
  TLM/TLM/Resources/lang_es.txt
  TLM/TLM/Resources/lang_fr.txt
  TLM/TLM/Resources/lang_it.txt
  TLM/TLM/Resources/lang_ja.txt
  TLM/TLM/Resources/lang_ko.txt
  TLM/TLM/Resources/lang_nl.txt
  TLM/TLM/Resources/lang_pl.txt
  TLM/TLM/Resources/lang_pt.txt
  TLM/TLM/Resources/lang_ru.txt
  TLM/TLM/Resources/lang_zh-tw.txt
  TLM/TLM/Resources/lang_zh.txt
  TLM/TLM/TLM.csproj
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/UI/IncompatibleModsPanel.cs
  TLM/TLM/UI/MainMenu/VersionLabel.cs
  TLM/TLM/Util/ModsCompatibilityChecker.cs
  TLM/TMPE.sln
Labels: LABS, UI, localisation, technical, usability, waiting
