Repository CitiesSkylinesMods/TMPE, pull requests merged in 2020-11, with the labels that each got.

#1028 Removed ProcessLane method, uint.ToLane() is used instead.
  TLM/TLM/Manager/Impl/LaneArrowManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/State/Flags.cs
  TLM/TMPE.CitiesGameBridge/Service/NetService.cs
  TLM/TMPE.GenericGameBridge/Service/INetService.cs
Labels: code cleanup, performance

#1027 Removed ProcessBuilding method that used a closure.
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Util/Shortcuts.cs
  TLM/TMPE.CitiesGameBridge/Service/BuildingService.cs
  TLM/TMPE.GenericGameBridge/Service/IBuildingService.cs
Labels: code cleanup, performance

#1029 Replaced ProcessNode(..) with ToNode() to remove closures.
  TLM/TLM/Manager/AbstractGeometryObservingManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/TrafficLightManager.cs
  TLM/TLM/Manager/Impl/TrafficLightSimulationManager.cs
  TLM/TLM/Manager/Impl/TrafficPriorityManager.cs
  TLM/TLM/Manager/Impl/TurnOnRedManager.cs
  TLM/TLM/State/Flags.cs
  TLM/TLM/Traffic/Impl/SegmentEnd.cs
  TLM/TLM/TrafficLight/Impl/CustomSegmentLight.cs
  TLM/TLM/TrafficLight/Impl/CustomSegmentLights.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLights.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLightsStep.cs
  TLM/TLM/UI/SubTools/PrioritySigns/PrioritySignsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ToggleTrafficLightsTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/SegmentTraverser.cs
  TLM/TMPE.CitiesGameBridge/Service/NetService.cs
  TLM/TMPE.GenericGameBridge/Service/INetService.cs
Labels: code cleanup, performance

#1023 Removed NetService.ProcessSegment by inlining the NetManager call.
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentManager.cs
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/ParkingRestrictionsManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/TurnOnRedManager.cs
  TLM/TLM/State/Flags.cs
  TLM/TLM/Traffic/Impl/SegmentEnd.cs
  TLM/TLM/TrafficLight/Impl/CustomSegmentLights.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLightsStep.cs
  TLM/TLM/UI/SubTools/PrioritySigns/PrioritySignsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/Util/SegmentLaneTraverser.cs
  TLM/TMPE.CitiesGameBridge/Service/NetService.cs
  TLM/TMPE.GenericGameBridge/Service/INetService.cs
Labels: code cleanup, performance

#993 Bugfix floating vehicles when Parking AI disabled
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TMPE.API/Manager/IAdvancedParkingManager.cs
Labels: 11 ALPHA, BUG, LABS, PARKING, STABLE

#1032 Right click to close main menu or exit current tool
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/UI/SubTools/JunctionRestrictionsTool.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/ManualTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ParkingRestrictionsTool.cs
  TLM/TLM/UI/SubTools/PrioritySigns/PrioritySignsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ToggleTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/Record/LaneConnectionRecord.cs
  TLM/TLM/Util/SegmentLaneTraverser.cs
  TLM/TMPE.CitiesGameBridge/Service/NetService.cs
Labels: Annoyance, Keybinds, Toolbar, Usability, enhancement

#1033 Release stable 11.5.1
  TLM/SharedAssemblyInfo.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Resources/RoadSelectionPanel/Clear-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Clear-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/HighPriority_LHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/HighPriority_LHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/HighPriority_RHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/HighPriority_RHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/RoundButton-bg-active.png
  TLM/TLM/Resources/RoadSelectionPanel/RoundButton-bg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/RoundButton-bg-hovered.png
  TLM/TLM/Resources/RoadSelectionPanel/RoundButton-bg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Roundabout_LHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Roundabout_LHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Roundabout_RHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Roundabout_RHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Stop_LHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Stop_LHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Stop_RHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Stop_RHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Yield_LHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Yield_LHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Yield_RHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Yield_RHT-fg-normal.png
  TLM/TLM/State/GlobalConfig.cs
  TLM/TLM/UI/SubTools/JunctionRestrictionsTool.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/ManualTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ParkingRestrictionsTool.cs
  TLM/TLM/UI/SubTools/PrioritySigns/PrioritySignsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ToggleTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/GenericObservable.cs
  TLM/TMPE.API/Manager/IAdvancedParkingManager.cs
Labels: STABLE

#1037 Fix RMB lane connector
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
Labels: BUG, Keybinds, LANE ROUTING, STABLE, confirmed
