Repository CitiesSkylinesMods/TMPE, pull requests merged in 2020-06, with the labels that each got.

#914 Remove CodeProfiler, SkyTools.Benchmark will serve the future.
  TLM/TLM/CodeProfiler.cs
  TLM/TLM/LoadingExtension.cs
  TLM/TLM/TLM.csproj
Labels: code cleanup, performance, technical

#915 Remove Finalizers
  TLM/TLM/LoadingExtension.cs
  TLM/TLM/Manager/AbstractGeometryObservingManager.cs
  TLM/TLM/Patch/_InfoManager/SetModePatch.cs
  TLM/TLM/Traffic/Impl/SegmentEnd.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLights.cs
  TLM/TLM/UI/ModUI.cs
Labels: code cleanup

#919 Fix stay-in-lane for MOM tracks
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
Labels: LANE ROUTING

#921 864 migrate Vehicle Spaw/Despawn patch harmony
  TLM/TLM/Custom/Data/CustomVehicle.cs
  TLM/TLM/Patch/_Vehicle/SpawnPatch.cs
  TLM/TLM/Patch/_Vehicle/UnspawnPatch.cs
  TLM/TLM/TLM.csproj
Labels: code cleanup

#922 added Unofficial.Microsoft.Unity.Analyzers nuget package.
  TLM/TLM/packages.config
Labels: EXTERNAL, code cleanup, meta

#906 LoopUtil.SpiralLoop replacement for better perf
  TLM/Benchmarks/App.config
  TLM/Benchmarks/Benchmarks.csproj
  TLM/Benchmarks/Program.cs
  TLM/Benchmarks/Properties/AssemblyInfo.cs
  TLM/Benchmarks/SpiralLoopPerfTests.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtPathManager.cs
  TLM/TLM/Util/LoopUtil.cs
  TLM/TMPE.UnitTest/TMPE.UnitTest.csproj
  TLM/TMPE.UnitTest/Util/LoopUtilTests.cs
  TLM/TMPE.sln
Labels: PARKING, PATHFINDER, performance

#928 Fix SA1111 warnings
  TLM/TLM/Custom/AI/CustomTrainAI.cs
  TLM/TLM/Custom/AI/CustomTramBaseAI.cs
  TLM/TLM/Custom/AI/CustomTrolleybusAI.cs
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/TrafficLight/Impl/CustomSegmentLight.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/Util/AutoTimedTrafficLights.cs
  TLM/TLM/Util/PriorityRoad.cs
Labels: code cleanup

#930 Fix SA1508 warnings
  TLM/TLM/Custom/AI/CustomPoliceCarAI.cs
  TLM/TLM/Custom/AI/CustomTramBaseAI.cs
  TLM/TLM/Manager/AbstractCustomManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/Manager/Impl/ParkingRestrictionsManager.cs
  TLM/TLM/Patch/_DefaultTool/RenderOverlayPatch.cs
  TLM/TLM/Patch/_InfoManager/SetModePatch.cs
  TLM/TLM/Patcher.cs
  TLM/TLM/State/OptionsTabs/OptionsGameplayTab.cs
  TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs
  TLM/TLM/State/OptionsTabs/OptionsOverlaysTab.cs
  TLM/TLM/State/OptionsTabs/OptionsVehicleRestrictionsTab.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLightsStep.cs
  TLM/TLM/UI/Helpers/CheckboxOption.cs
  TLM/TLM/UI/Helpers/SerializableUIOptionBase.cs
  TLM/TLM/UI/Localization/LookupTable.cs
  TLM/TLM/UI/RemoveCitizenInstanceButtonExtender.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/MphSignStyle.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/Util/RoundaboutMassEdit.cs
  TLM/TLM/Util/SegmentLaneTraverser.cs
  TLM/TLM/Util/SeparateTurningLanesUtil.cs
  TLM/TMPE.UnitTest/Translation/CsvParser.cs
Labels: code cleanup

#932 more precise lane connector overlays.
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
Labels: LANE ROUTING, UI

#940 Fix warnings ide0003 2nd try
  TLM/.editorconfig
  TLM/TLM/U/Autosize/UResizer.cs
  TLM/TLM/U/Button/BaseUButton.cs
  TLM/TLM/U/Button/UButton.cs
  TLM/TLM/U/Label/ULabel.cs
  TLM/TLM/U/Panel/BaseUWindowPanel.cs
  TLM/TLM/UI/Helpers/CheckboxOption.cs
  TLM/TLM/UI/LegacySubTool.cs
  TLM/TLM/UI/MainMenu/DespawnButton.cs
  TLM/TLM/UI/MainMenu/MainMenuButton.cs
  TLM/TLM/UI/MainMenu/MainMenuWindow.cs
  TLM/TLM/UI/MainMenu/StatsLabel.cs
  TLM/TLM/UI/RemoveCitizenInstanceButtonExtender.cs
  TLM/TLM/UI/RemoveVehicleButtonExtender.cs
  TLM/TLM/UI/RoadSelectionPanels.cs
  TLM/TLM/UI/SubTools/JunctionRestrictionsTool.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowButton.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowToolWindow.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/UITransportDemand.cs
Labels: code cleanup

#933 Make it easier to debug harmony problems
  TLM/TLM/Patcher.cs
  TLM/TLM/TrafficManagerMod.cs
Labels: Harmony, technical

#920 Apply Shift+Click speed limit to entire roundabout
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
Labels: SPEED LIMITS

#948 Fix warnings undo ide0003
  TLM/.editorconfig
  TLM/TLM/U/Autosize/UResizer.cs
  TLM/TLM/U/Button/BaseUButton.cs
  TLM/TLM/U/Button/UButton.cs
  TLM/TLM/U/Label/ULabel.cs
  TLM/TLM/U/Panel/BaseUWindowPanel.cs
  TLM/TLM/UI/Helpers/CheckboxOption.cs
  TLM/TLM/UI/LegacySubTool.cs
  TLM/TLM/UI/MainMenu/DespawnButton.cs
  TLM/TLM/UI/MainMenu/MainMenuButton.cs
  TLM/TLM/UI/MainMenu/MainMenuWindow.cs
  TLM/TLM/UI/MainMenu/StatsLabel.cs
  TLM/TLM/UI/RemoveCitizenInstanceButtonExtender.cs
  TLM/TLM/UI/RemoveVehicleButtonExtender.cs
  TLM/TLM/UI/RoadSelectionPanels.cs
  TLM/TLM/UI/SubTools/JunctionRestrictionsTool.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowButton.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowToolWindow.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/UITransportDemand.cs
Labels: code cleanup

#929 Remove `#if PARKINGAI`
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/TLM.csproj
Labels: code cleanup

#950 Switched from Unofficial.Microsoft.Unity.Analyzers to Microsoft.Unity…
  TLM/TLM/TLM.csproj
  TLM/TLM/packages.config
Labels: code cleanup

#957 catch null segment info
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
Labels: BUG, technical

#938 TMPE tool should behave when returning from free camera view
  TLM/TLM/ThreadingExtension.cs
  TLM/TLM/UI/ModUI.cs
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: BUG, UI, code cleanup

#956 Move IT support
  TLM/SharedAssemblyInfo.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Util/Record/IRecordable.cs
  TLM/TLM/Util/Record/LaneArrowsRecord.cs
  TLM/TLM/Util/Record/LaneConnectionRecord.cs
  TLM/TLM/Util/Record/NodeRecord.cs
  TLM/TLM/Util/Record/RecordUtil.cs
  TLM/TLM/Util/Record/SegmentEndRecord.cs
  TLM/TLM/Util/Record/SegmentRecord.cs
  TLM/TLM/Util/Record/SpeedLimitLaneRecord.cs
  TLM/TLM/Util/Record/TrafficRulesRecord.cs
  TLM/TLM/Util/Shortcuts.cs
Labels: COMPATIBILITY, EXTERNAL, high priority, technical

#965 fixed typo in lane record
  TLM/TLM/Util/Record/SegmentEndRecord.cs
  TLM/TLM/Util/Record/SegmentRecord.cs
Labels: BUG, serialization

#964 load TMPE in asset editor
  TLM/TLM/LoadingExtension.cs
  TLM/TLM/Patch/_DefaultTool/OnToolGUIPatch.cs
  TLM/TLM/Patch/_DefaultTool/RenderOverlayPatch.cs
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: Blocking, feature, serialization
