Repository CitiesSkylinesMods/TMPE, pull requests merged in 2020-01, with the labels that each got.

#605 Bugfix - remove Timed Traffic Lights from group
  TLM/TLM/Manager/Impl/TrafficLightSimulationManager.cs
  TLM/TLM/UI/SubTools/TimedTrafficLightsTool.cs
Labels: BUG, TRAFFIC LIGHTS

#603 Translations update
  TLM/TLM/Resources/Translations/AI_Citizen.csv
  TLM/TLM/Resources/Translations/LaneRouting.csv
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/Resources/Translations/ModConflicts.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
  TLM/TLM/Resources/Translations/Tutorials.csv
  TLM/TLM/Resources/Translations/VehicleRestrictions.csv
Labels: Localisation, UI

#607 Add additional check if hovered node and segments are connected,
  TLM/TLM/UI/SubTools/LaneArrowTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: 11 ALPHA, LANE ROUTING, UI, Usability

#610 Update incompatible mods
  TLM/TLM/Resources/incompatible_mods.txt
Labels: COMPATIBILITY, EXTERNAL

#614 Incompatible mod: Trees Respiration
  TLM/TLM/Resources/incompatible_mods.txt
Labels: COMPATIBILITY, EXTERNAL

#627 Update incompatible_mods.txt
  TLM/TLM/Resources/incompatible_mods.txt
Labels: COMPATIBILITY
