Repository CitiesSkylinesMods/TMPE, pull requests merged in 2020-10, with the labels that each got.

#966 record vehicle restrictions
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Util/Record/SegmentRecord.cs
  TLM/TLM/Util/Record/VehicleRestrictionsLaneRecord.cs
Labels: EXTERNAL, serialization

#1003 no double crossing policy
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/OptionsVehicleRestrictionsTab.cs
  TLM/TLM/UI/Helpers/CheckboxOption.cs
  TLM/TLM/Util/PriorityRoad.cs
  TLM/TLM/Util/Shortcuts.cs
Labels: Annoyance, JUNCTION RESTRICTIONS, Pedestiran Crossing, Settings, feature

#1019 Deprecated SpiralLoop cleanup.
  TLM/Benchmarks/Benchmarks.csproj
  TLM/Benchmarks/LoopUtilPerfTests.cs
  TLM/Benchmarks/Program.cs
  TLM/Benchmarks/SpiralLoopPerfTests.cs
  TLM/Benchmarks/SpiralPerfTests.cs
  TLM/TLM/Util/LoopUtil.cs
  TLM/TMPE.UnitTest/Util/LoopUtilTests.cs
Labels: code cleanup
