Repository CitiesSkylinesMods/TMPE, pull requests merged in 2020-03, with the labels that each got.

#751 Managed dll locations for EA Origin builds
  docs/BUILDING_INSTRUCTIONS.md
Labels: docs, meta

#765 Created missing despawn buttons
  TLM/TLM/Resources/Clear/Clear-bg-active.png
  TLM/TLM/Resources/Clear/Clear-bg-hovered.png
  TLM/TLM/Resources/Clear/Clear-bg-normal.png
  TLM/TLM/Resources/Clear/Clear-fg-active.png
  TLM/TLM/Resources/Clear/Clear-fg-hovered.png
  TLM/TLM/Resources/Clear/Clear-fg-normal.png
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/RemoveCitizenInstanceButtonExtender.cs
  TLM/TLM/UI/RemoveVehicleButtonExtender.cs
Labels: DESPAWN TOOLS, LABS, UI

#761 Yield behaviour improvements
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
Labels: PRIORITY SIGNS, enhancement

#766 Changelog for 11.1.1-hotfix1
  CHANGELOG.md
  README.md
Labels: docs, meta

#768 Fix typo in tag compare URLs in changelog
  CHANGELOG.md
  README.md
Labels: docs, meta

#770 fixed the direction of auto-TTL for RHT
  TLM/TLM/Util/AutoTimedTrafficLights.cs
Labels: TRAFFIC LIGHTS

#771 update changelog + bump mod to v11.1.2
  CHANGELOG.md
  README.md
  TLM/SharedAssemblyInfo.cs
Labels: docs, meta

#774 Small class to display warning and error prompts
  TLM/TLM/State/Keybinds/KeybindUI.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/ThreadingExtension.cs
  TLM/TLM/UI/Helpers/Prompt.cs
  TLM/TLM/UI/SubTools/ManualTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/PrioritySignsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ToggleTrafficLightsTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: UI, code cleanup

#776 Remove duplicate xcopy in post-build script
  TLM/TLM/TLM.csproj
Labels: code cleanup

#777 Fix some typos in changelog
  CHANGELOG.md
Labels: docs, meta

#779 Update early entries of changelog
  CHANGELOG.md
Labels: docs

#794 Compatibility with Sunset Harbor
  TLM/SharedAssemblyInfo.cs
  TLM/TLM/Custom/AI/CustomRoadBaseAI.cs
  TLM/TLM/Custom/AI/CustomTransportLineAI.cs
  TLM/TLM/Custom/AI/CustomTrolleybusAI.cs
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/Custom/PathFinding/CustomPathManager.cs
  TLM/TLM/Custom/PathFinding/StockPathFind.cs
  TLM/TLM/LoadingExtension.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentManager.cs
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Traffic/ExtVehicleType.cs
  TLM/TLM/TrafficManagerMod.cs
  TLM/TMPE.API/Traffic/Enums/ExtVehicleType.cs
Labels: LABS, STABLE

#800 Update changelog & readme for 11.2.0 & 11.2.1 release
  CHANGELOG.md
  README.md
Labels: docs

#806 Update game version badges
  README.md
  docs/index.md
Labels: docs, meta
