Repository CitiesSkylinesMods/TMPE, pull requests merged in 2020-05, with the labels that each got.

#868 Onscreen Hints for more tools
  TLM/TLM/Resources/Translations/Guide.csv
  TLM/TLM/Resources/Translations/JunctionRestrictions.csv
  TLM/TLM/Resources/Translations/LaneRouting.csv
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/ParkingRestrictions.csv
  TLM/TLM/Resources/Translations/PrioritySigns.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
  TLM/TLM/Resources/Translations/VehicleRestrictions.csv
  TLM/TLM/State/Keybinds/KeybindSettingsBase.cs
  TLM/TLM/State/Keybinds/KeybindSettingsPage.cs
  TLM/TLM/State/OptionsTabs/OptionsGameplayTab.cs
  TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs
  TLM/TLM/U/Button/BaseUButton.cs
  TLM/TLM/U/UIUtil.cs
  TLM/TLM/UI/LegacySubTool.cs
  TLM/TLM/UI/Localization/LookupTable.cs
  TLM/TLM/UI/MainMenu/BaseMenuButton.cs
  TLM/TLM/UI/MainMenu/BaseMenuToolModeButton.cs
  TLM/TLM/UI/MainMenu/ClearTrafficButton.cs
  TLM/TLM/UI/MainMenu/DespawnButton.cs
  TLM/TLM/UI/MainMenu/MainMenuWindow.cs
  TLM/TLM/UI/MainMenu/OSD/OnscreenDisplay.cs
  TLM/TLM/UI/MainMenu/ParkingRestrictionsButton.cs
  TLM/TLM/UI/MainMenu/PrioritySignsButton.cs
  TLM/TLM/UI/MainMenu/TimedTrafficLightsButton.cs
  TLM/TLM/UI/SubTools/JunctionRestrictionsTool.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/ManualTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ParkingRestrictionsTool.cs
  TLM/TLM/UI/SubTools/PrioritySigns/PrioritySignsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ToggleTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
Labels: JUNCTION RESTRICTIONS, PARKING, PRIORITY SIGNS, SPEED LIMITS, TRAFFIC LIGHTS, Toolbar, UI, Usability, VEHICLE RESTRICTIONS

#880 Careful updating of tooltips; Correct reset of timed TL UI
  TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
Labels: BUG, Settings, TRAFFIC LIGHTS, UI

#883 Fix `CalculateCorner()` exception when `NetInfo` is `null`
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
Labels: Overlays

#891 fixed lane arrows reset check for lane connections on RHT
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
Labels: LANE ROUTING

#892 Icon design
  TLM/TLM/Resources/RoadSelectionPanel/HighPriority-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/HighPriority-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/HighPriority_LHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/HighPriority_LHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/HighPriority_RHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/HighPriority_RHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Roundabout-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Roundabout-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Roundabout_LHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Roundabout_LHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Roundabout_RHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Roundabout_RHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Stop-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Stop-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Stop_LHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Stop_LHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Stop_RHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Stop_RHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Yield-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Yield-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Yield_LHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Yield_LHT-fg-normal.png
  TLM/TLM/Resources/RoadSelectionPanel/Yield_RHT-fg-disabled.png
  TLM/TLM/Resources/RoadSelectionPanel/Yield_RHT-fg-normal.png
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/RoadSelectionPanels.cs
  TLM/TLM/UI/Textures/TextureResources.cs
Labels: LANE ROUTING, MASS EDIT, PRIORITY SIGNS, UI, Usability

#884 V11.5.0
  CHANGELOG.md
  README.md
  TLM/SharedAssemblyInfo.cs
Labels: docs, meta

#863 more roundabout quick setup features
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/Manager/Impl/ParkingRestrictionsManager.cs
  TLM/TLM/Manager/Impl/SegmentEndManager.cs
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/Patch/_RoadWorldInfoPanel/OnAdjustRoadButtonPatch.cs
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/PrioritySigns.csv
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/OptionsMassEditTab.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/Helpers/CheckboxOption.cs
  TLM/TLM/UI/Helpers/SerializableUIOptionBase.cs
  TLM/TLM/UI/RoadSelectionPanels.cs
  TLM/TLM/UI/SubTools/ParkingRestrictionsTool.cs
  TLM/TLM/UI/SubTools/PrioritySigns/PrioritySignsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/PriorityRoad.cs
  TLM/TLM/Util/Record/IRecordable.cs
  TLM/TLM/Util/Record/LaneArrowsRecord.cs
  TLM/TLM/Util/Record/LaneConnectionRecord.cs
  TLM/TLM/Util/Record/NodeRecord.cs
  TLM/TLM/Util/Record/SegmentEndRecord.cs
  TLM/TLM/Util/Record/SegmentRecord.cs
  TLM/TLM/Util/Record/SpeedLimitLaneRecord.cs
  TLM/TLM/Util/Record/TrafficRulesRecord.cs
  TLM/TLM/Util/RoundaboutMassEdit.cs
  TLM/TLM/Util/SegmentTraverser.cs
  TLM/TLM/Util/Shortcuts.cs
Labels: JUNCTION RESTRICTIONS, Localisation, PARKING, PRIORITY SIGNS, SPEED LIMITS, UI

#903 Changelogs for STABLE 11.4.0 update
  CHANGELOG.md
  README.md
Labels: docs, meta

#904 Fix "Priority roads.Tooltip:Allow far turns" string message
  TLM/TLM/State/OptionsTabs/OptionsMassEditTab.cs
Labels: Localisation, MASS EDIT, PRIORITY SIGNS, UI

#909 GenericObservable - Use locks; Reuse existing list
  TLM/TLM/State/GlobalConfig.cs
  TLM/TLM/Util/GenericObservable.cs
Labels: code cleanup, performance

#907 Skytools benchmark
  TLM/CSUtil.Commons/Benchmark/Benchmark.cs
  TLM/CSUtil.Commons/Benchmark/BenchmarkProfile.cs
  TLM/CSUtil.Commons/Benchmark/BenchmarkProfileProvider.cs
  TLM/CSUtil.Commons/CSUtil.Commons.csproj
  TLM/TLM/Benchmark/BenchmarkManager.cs
  TLM/TLM/Custom/AI/CustomCarAI.cs
  TLM/TLM/Custom/AI/CustomFireTruckAI.cs
  TLM/TLM/Custom/AI/CustomHumanAI.cs
  TLM/TLM/Custom/AI/CustomPassengerCarAI.cs
  TLM/TLM/LoadingExtension.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/Manager/Impl/TrafficLightSimulationManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Patch/_RoadBaseAI/SegmentSimulationStepPatch.cs
  TLM/TLM/State/OptionsTabs/OptionsMaintenanceTab.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/ThreadingExtension.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLightsStep.cs
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/packages.config
  TLM/TMPE.CitiesGameBridge/TMPE.CitiesGameBridge.csproj
  TLM/TMPE.GenericGameBridge/TMPE.GenericGameBridge.csproj
  TLM/TMPE.TestGameBridge/TMPE.TestGameBridge.csproj
  TLM/TMPE.UnitTest/TMPE.UnitTest.csproj
  TLM/TMPE.sln
Labels: code cleanup, performance

#917 fixed SA1413 UseTrailingCommasInMultiLineInitializers
  TLM/CSUtil.Commons/Log.cs
  TLM/CSUtil.Commons/TernaryBool.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/Manager/Impl/ExtNodeManager.cs
  TLM/TLM/Manager/Impl/ParkingRestrictionsManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/TrafficLightSimulationManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/State/OptionsTabs/OptionsGameplayTab.cs
  TLM/TLM/State/OptionsTabs/OptionsVehicleRestrictionsTab.cs
  TLM/TLM/Traffic/ExtVehicleType.cs
  TLM/TLM/UI/Localization/Translation.cs
  TLM/TLM/UI/RemoveCitizenInstanceButtonExtender.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedUnit.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/UI/TrafficManagerMode.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/UI/TransportDemandViewMode.cs
  TLM/TLM/Util/AutoTimedTrafficLights.cs
  TLM/TLM/Util/SegmentLaneTraverser.cs
  TLM/TLM/Util/SegmentTraverser.cs
  TLM/TMPE.API/Traffic/Enums/CarUsagePolicy.cs
  TLM/TMPE.API/Traffic/Enums/EmergencyBehavior.cs
  TLM/TMPE.API/Traffic/Enums/ExtParkingSpaceLocation.cs
  TLM/TMPE.API/Traffic/Enums/ExtPathState.cs
  TLM/TMPE.API/Traffic/Enums/ExtPathType.cs
  TLM/TMPE.API/Traffic/Enums/ExtSoftPathState.cs
  TLM/TMPE.API/Traffic/Enums/ExtTransportMode.cs
  TLM/TMPE.API/Traffic/Enums/ExtVehicleFlags.cs
  TLM/TMPE.API/Traffic/Enums/FlowWaitCalcMode.cs
  TLM/TMPE.API/Traffic/Enums/GeometryCalculationMode.cs
  TLM/TMPE.API/Traffic/Enums/LaneEndTransitionType.cs
  TLM/TMPE.API/Traffic/Enums/LightMode.cs
  TLM/TMPE.API/Traffic/Enums/ParkedCarApproachState.cs
  TLM/TMPE.API/Traffic/Enums/ParkingError.cs
  TLM/TMPE.API/Traffic/Enums/PriorityType.cs
  TLM/TMPE.API/Traffic/Enums/SetLaneArrow_Result.cs
  TLM/TMPE.API/Traffic/Enums/SetPrioritySignError.cs
  TLM/TMPE.API/Traffic/Enums/SimulationAccuracy.cs
  TLM/TMPE.API/Traffic/Enums/ToggleTrafficLightError.cs
  TLM/TMPE.API/Traffic/Enums/TrafficLightSimulationType.cs
  TLM/TMPE.API/Traffic/Enums/VehicleJunctionTransitState.cs
  TLM/TMPE.API/Traffic/Enums/VehicleRestrictionsAggression.cs
  TLM/TMPE.API/Traffic/Enums/VehicleRestrictionsMode.cs
  TLM/TMPE.GenericGameBridge/Service/INetService.cs
  TLM/TMPE.UnitTest/Util/TinyDictionaryUnitTest.cs
Labels: code cleanup
