Repository CitiesSkylinesMods/TMPE, pull requests merged in 2021-04, with the labels that each got.

#1068 cleaning up life cycle code
  TLM/TLM/LoadingExtension.cs
  TLM/TLM/Patcher.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/SerializableDataExtension.cs
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/UI/Helpers/ExtUITabStrip.cs
  TLM/TLM/UI/MainMenu/MainMenuWindow.cs
Labels: code cleanup

#1069 Fixed SA1410 warnings by replacing the delegates with lambdas.
  TLM/TLM/Patch/_InfoManager/SetModePatch.cs
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/UI/Helpers/GuideHandler.cs
  TLM/TLM/UI/RoadSelectionPanels.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/RoadSelectionUtil.cs
Labels: code cleanup

#1071 Fixed all instances of delegate instance allocation (HAA0603) where i…
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
Labels: code cleanup, performance

#1080 Hide overlays if no longer necessary
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: BUG, MASS EDIT, Overlays

#1079 Main Camera cache reinitialization to prevent use of inactive camera
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/InGameUtil.cs
Labels: BUG, LANE ROUTING, performance

#1072 730 cleanup loading custom path manager
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/Custom/PathFinding/CustomPathManager.cs
  TLM/TLM/LoadingExtension.cs
  TLM/TLM/Patcher.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/TrafficManagerMod.cs
  TLM/TLM/UI/Helpers/ExtUITabStrip.cs
Labels: Blocking, code cleanup, enhancement

#1076 harmon patcher continues on error
  TLM/TLM/Custom/PathFinding/CustomPathManager.cs
  TLM/TLM/Patcher.cs
  TLM/TLM/Util/Shortcuts.cs
Labels: Blocking, Harmony, enhancement

#1090 Translation update
  TLM/TLM/Resources/Translations/AI_Car.csv
  TLM/TLM/Resources/Translations/AI_Citizen.csv
  TLM/TLM/Resources/Translations/Guide.csv
  TLM/TLM/Resources/Translations/JunctionRestrictions.csv
  TLM/TLM/Resources/Translations/LaneRouting.csv
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/Resources/Translations/ModConflicts.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/ParkingRestrictions.csv
  TLM/TLM/Resources/Translations/PrioritySigns.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
  TLM/TLM/Resources/Translations/Tutorials.csv
  TLM/TLM/Resources/Translations/VehicleRestrictions.csv
Labels: Localisation

#1094 Moved foreach even one further level out to fix the bug with multiple…
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
Labels: BUG

#1093 More Vehicles compatibility fix
  TLM/TLM/Lifecycle/SerializableDataExtension.cs
  TLM/TLM/Lifecycle/TMPELifecycle.cs
Labels: COMPATIBILITY, Harmony, high priority
