Repository CitiesSkylinesMods/TMPE, pull requests merged in 2021-11, with the labels that each got.

#1189 Priority signs tool not working
  TLM/TLM/Manager/Impl/TrafficPriorityManager.cs
Labels: BUG, confirmed, PRIORITY SIGNS, regression

#1196 Incompatible detector improvements
  TLM/TLM/Resources/incompatible_mods.txt
  TLM/TLM/UI/IncompatibleModsPanel.cs
  TLM/TLM/Util/ModsCompatibilityChecker.cs
Labels: enhancement, COMPATIBILITY

#1194 Remove NetService and the GameBridge stuff
  TLM/Benchmarks/Benchmarks.csproj
  TLM/Benchmarks/GetNodeSegmentIdsEnumerablePerfTests.cs
  TLM/Benchmarks/GetSegmentLaneIdAndSegmentPerfTests.cs
  TLM/TLM/Constants.cs
  TLM/TLM/Manager/AbstractCustomManager.cs
  TLM/TLM/Manager/Impl/ClockDirection.cs
  TLM/TLM/Manager/Impl/ExtNodeManager.cs
  TLM/TLM/Manager/Impl/ExtPathManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentManager.cs
  TLM/TLM/Manager/Impl/GetNodeSegmentIdsEnumerable.cs
  TLM/TLM/Manager/Impl/GetNodeSegmentIdsEnumerator.cs
  TLM/TLM/Manager/Impl/GetSegmentLaneIdsEnumerable.cs
  TLM/TLM/Manager/Impl/GetSegmentLaneIdsEnumerator.cs
  TLM/TLM/Manager/Impl/LaneArrowManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/LaneIdAndIndex.cs
  TLM/TLM/Manager/Impl/LanePos.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/SegmentEndManager.cs
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/State/Flags.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Traffic/Impl/SegmentEnd.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLights.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/ParkingRestrictionsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/Util/AutoTimedTrafficLights.cs
  TLM/TLM/Util/PriorityRoad.cs
  TLM/TLM/Util/Record/LaneArrowsRecord.cs
  TLM/TLM/Util/Record/LaneConnectionRecord.cs
  TLM/TLM/Util/Record/SegmentRecord.cs
  TLM/TLM/Util/Record/SpeedLimitLaneRecord.cs
  TLM/TLM/Util/Record/VehicleRestrictionsLaneRecord.cs
  TLM/TLM/Util/RoundaboutMassEdit.cs
  TLM/TLM/Util/SegmentLaneTraverser.cs
  TLM/TLM/Util/SeparateTurningLanesUtil.cs
  TLM/TLM/Util/Shortcuts.cs
  TLM/TMPE.API/Manager/ICustomManager.cs
  TLM/TMPE.API/TMPE.API.csproj
  TLM/TMPE.CitiesGameBridge/Factory/ServiceFactory.cs
  TLM/TMPE.CitiesGameBridge/Properties/AssemblyInfo.cs
  TLM/TMPE.CitiesGameBridge/Service/NetService.cs
  TLM/TMPE.CitiesGameBridge/TMPE.CitiesGameBridge.csproj
  TLM/TMPE.CitiesGameBridge/packages.config
  TLM/TMPE.GenericGameBridge/Factory/IServiceFactory.cs
  TLM/TMPE.GenericGameBridge/Properties/AssemblyInfo.cs
  TLM/TMPE.GenericGameBridge/Service/INetService.cs
  TLM/TMPE.GenericGameBridge/TMPE.GenericGameBridge.csproj
  TLM/TMPE.GenericGameBridge/packages.config
  TLM/TMPE.UnitTest/TMPE.UnitTest.csproj
  TLM/TMPE.UnitTest/Util/GetNodeSegmentIdsEnumerableTests.cs
  TLM/TMPE.sln
Labels: code cleanup

#1199 Fixed recalculation after lane connection remove
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
Labels: BUG, confirmed, LANE ROUTING

#1197 Refactoring/IsValid
  TLM/Benchmarks/Benchmarks.csproj
  TLM/Benchmarks/IsValidPerfTests.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/CustomSegmentLightsManager.cs
  TLM/TLM/Manager/Impl/ExtBuildingManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/Manager/Impl/ExtNodeManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentManager.cs
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/GeometryManager.cs
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/LaneArrowManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/SegmentEndManager.cs
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/Manager/Impl/TrafficLightManager.cs
  TLM/TLM/Manager/Impl/TrafficLightSimulationManager.cs
  TLM/TLM/Manager/Impl/TrafficPriorityManager.cs
  TLM/TLM/Manager/Impl/TurnOnRedManager.cs
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/State/Asset/AssetData.cs
  TLM/TLM/State/Flags.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Traffic/Impl/SegmentEnd.cs
  TLM/TLM/TrafficLight/Impl/CustomSegmentLight.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLights.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLightsStep.cs
  TLM/TLM/UI/SubTools/JunctionRestrictionsTool.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/ParkingRestrictionsTool.cs
  TLM/TLM/UI/SubTools/PrioritySigns/PrioritySignsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ToggleTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/Util/Extensions/BuildingExtensions.cs
  TLM/TLM/Util/Extensions/CitizenExtensions.cs
  TLM/TLM/Util/Extensions/CitizenInstanceExtensions.cs
  TLM/TLM/Util/Extensions/FlagsExtensions.cs
  TLM/TLM/Util/Extensions/NetLaneExtensions.cs
  TLM/TLM/Util/Extensions/NetNodeExtensions.cs
  TLM/TLM/Util/Extensions/NetSegmentExtensions.cs
  TLM/TLM/Util/Extensions/VehicleExtensions.cs
  TLM/TLM/Util/Shortcuts.cs
  TLM/TMPE.API/Manager/IExtBuildingManager.cs
  TLM/TMPE.API/Manager/IExtCitizenInstanceManager.cs
  TLM/TMPE.API/Manager/IExtNodeManager.cs
  TLM/TMPE.API/Manager/IExtSegmentManager.cs
Labels: code cleanup

#1204 Converted almost all .m_segments.m_buffer[segmentId] calls to segment…
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/CustomSegmentLightsManager.cs
  TLM/TLM/Manager/Impl/ExtPathManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentManager.cs
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/Manager/Impl/TrafficPriorityManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/Notifier.cs
  TLM/TLM/Patch/_CitizenAI/_HumanAI/CheckTrafficLightsPatch.cs
  TLM/TLM/Patch/_VehicleAI/UpdatePathTargetPositionsPatch.cs
  TLM/TLM/Patch/_VehicleAI/VehicleAICommons.cs
  TLM/TLM/Patch/_VehicleAI/_CarAI/CalculateSegmentPositionPatch.cs
  TLM/TLM/Patch/_VehicleAI/_CarAI/CalculateSegmentPositionPatch2.cs
  TLM/TLM/Patch/_VehicleAI/_TrainAI/CheckNextLanePatch.cs
  TLM/TLM/Patch/_VehicleAI/_TrainAI/ForceTrafficLightsPatch.cs
  TLM/TLM/Patch/_VehicleAI/_TrainAI/SimulationStep2Patch.cs
  TLM/TLM/Patch/_VehicleAI/_TramBaseAI/CalculateSegmentPositionPatch2.cs
  TLM/TLM/State/Flags.cs
  TLM/TLM/TrafficLight/Impl/CustomSegmentLight.cs
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/ManualTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ParkingRestrictionsTool.cs
  TLM/TLM/UI/SubTools/PrioritySigns/PrioritySignsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/AutoTimedTrafficLights.cs
  TLM/TLM/Util/GeometryUtil.cs
  TLM/TLM/Util/SeparateTurningLanesUtil.cs
Labels: code cleanup
