Repository CitiesSkylinesMods/TMPE, pull requests merged in 2021-02, with the labels that each got.

#1056 its not like anyone will miss an empty project right?
  TLM/TMPE.TestGameBridge/Properties/AssemblyInfo.cs
  TLM/TMPE.TestGameBridge/TMPE.TestGameBridge.csproj
  TLM/TMPE.TestGameBridge/packages.config
  TLM/TMPE.sln
Labels: code cleanup

#1057 old stuff that should have been deleted earlier.
  TLM/TMPE.SpiralLoopTest/App.config
  TLM/TMPE.SpiralLoopTest/Program.cs
  TLM/TMPE.SpiralLoopTest/Properties/AssemblyInfo.cs
  TLM/TMPE.SpiralLoopTest/SpiralLoopTest.csproj
Labels: code cleanup

#1058 Fixed all instances of "SA1507 Code should not contain multiple blank…
  TLM/TLM/Custom/AI/CustomTrolleybusAI.cs
  TLM/TLM/Custom/PathFinding/CustomPathManager.cs
  TLM/TLM/LoadingExtension.cs
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/State/OptionsTabs/OptionsVehicleRestrictionsTab.cs
  TLM/TLM/Traffic/Impl/SegmentEnd.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLights.cs
  TLM/TLM/UI/Localization/Translation.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/ParkingRestrictionsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/AutoTimedTrafficLights.cs
  TLM/TLM/Util/PriorityRoad.cs
  TLM/TLM/Util/RoundaboutMassEdit.cs
  TLM/TMPE.API/Manager/IExtSegmentEndManager.cs
  TLM/TMPE.API/Manager/IJunctionRestrictionsManager.cs
  TLM/TMPE.GenericGameBridge/Service/INetService.cs
Labels: code cleanup

#1054 Unity profiler support with various improvements
  TLM/TLM/LoadingExtension.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/Helpers/NodeLaneMarker.cs
  TLM/TLM/UI/Helpers/SegmentLaneMarker.cs
  TLM/TLM/UI/LegacySubTool.cs
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/UI/ModUI.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/ManualTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ParkingRestrictionsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ToggleTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/Util/GeometryUtil.cs
  TLM/TLM/Util/InGameUtil.cs
Labels: code cleanup, enhancement, performance, technical

#1055 Closure killer for IterateNodeSegments
  TLM/Benchmarks/Benchmarks.csproj
  TLM/Benchmarks/GetNodeSegmentIdsEnumerablePerfTests.cs
  TLM/Benchmarks/Program.cs
  TLM/TLM/Manager/Impl/CustomSegmentLightsManager.cs
  TLM/TLM/Manager/Impl/ExtNodeManager.cs
  TLM/TLM/Manager/Impl/GeometryManager.cs
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/TrafficLightManager.cs
  TLM/TLM/Manager/Impl/TrafficPriorityManager.cs
  TLM/TLM/Manager/Impl/TurnOnRedManager.cs
  TLM/TLM/TrafficLight/Impl/TimedTrafficLights.cs
  TLM/TLM/UI/SubTools/JunctionRestrictionsTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/AutoTimedTrafficLights.cs
  TLM/TLM/Util/PriorityRoad.cs
  TLM/TLM/Util/RoundaboutMassEdit.cs
  TLM/TLM/Util/SeparateTurningLanesUtil.cs
  TLM/TMPE.CitiesGameBridge/Service/NetService.cs
  TLM/TMPE.GenericGameBridge/Service/GetNodeSegmentIdsEnumerable.cs
  TLM/TMPE.GenericGameBridge/Service/GetNodeSegmentIdsEnumerator.cs
  TLM/TMPE.GenericGameBridge/Service/INetService.cs
  TLM/TMPE.GenericGameBridge/TMPE.GenericGameBridge.csproj
  TLM/TMPE.UnitTest/TMPE.UnitTest.csproj
  TLM/TMPE.UnitTest/Util/GetNodeSegmentIdsEnumerableTests.cs
Labels: code cleanup, performance

#1047 New languages, update existing
  TLM/TLM/Resources/Translations/AI_Car.csv
  TLM/TLM/Resources/Translations/AI_Citizen.csv
  TLM/TLM/Resources/Translations/Guide.csv
  TLM/TLM/Resources/Translations/JunctionRestrictions.csv
  TLM/TLM/Resources/Translations/LaneRouting.csv
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/Resources/Translations/ModConflicts.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/ParkingRestrictions.csv
  TLM/TLM/Resources/Translations/PrioritySigns.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
  TLM/TLM/Resources/Translations/Tutorials.csv
  TLM/TLM/Resources/Translations/VehicleRestrictions.csv
  TLM/TLM/UI/Localization/Translation.cs
Labels: Localisation, UI, Usability

#1059 CitiesHarmony API upgrade
  TLM/TLM/TLM.csproj
  TLM/TLM/packages.config
Labels: code cleanup, technical
