Repository CitiesSkylinesMods/TMPE, pull requests merged in 2021-05, with the labels that each got.

#1091 Citizen not found fix
  TLM/TLM/Patch/_CitizenAI/_HumanAI/SimulationStepPatch.cs
Labels: BUG, LABS, PARKING, PATHFINDER, STABLE, confirmed

#1103 Version bump, compatibility fix for new BloodyPenguin's mod
  TLM/SharedAssemblyInfo.cs
  TLM/TLM/Custom/AI/CustomCargoTruckAI.cs
  TLM/TLM/Custom/AI/CustomPostVanAI.cs
Labels: STABLE

#1105 Stable 11.5.2 cargo truck PF fix
  TLM/TLM/Custom/AI/CustomCargoTruckAI.cs
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/TrafficManagerMod.cs
Labels: STABLE

#1096 1095 asset lifecycle
  TLM/TLM/Lifecycle/AssetDataExtension.cs
  TLM/TLM/Lifecycle/LoadingExtension.cs
  TLM/TLM/Lifecycle/Patcher.cs
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/Lifecycle/TrafficManagerMod.cs
  TLM/TLM/Patch/_LoadAssetPanel/OnLoadPatch.cs
  TLM/TLM/State/Asset/AssetData.cs
  TLM/TLM/State/Asset/AssetDataExtension.cs
  TLM/TLM/State/Flags.cs
  TLM/TLM/State/TMPEMoveITIntegration.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/UI/ModUI.cs
  TLM/TLM/Util/PlaceIntersectionUtil.cs
  TLM/TLM/Util/VersionUtil.cs
  TLM/TMPE.sln
Labels: BUG, code cleanup, enhancement

#1108 11.5.2 to master
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
Labels: COMPATIBILITY, STABLE

#1098 Rename LABS to TEST, prepare release to the Workshop
  TLM/SharedAssemblyInfo.cs
  TLM/TLM/Lifecycle/TrafficManagerMod.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Util/VersionUtil.cs
  TLM/TMPE.sln
Labels: technical

#1112 11.5.2-hotfix-2
  TLM/TLM/Custom/AI/CustomCargoTruckAI.cs
  TLM/TLM/Custom/AI/CustomPostVanAI.cs
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/Manager/Impl/TrafficLightManager.cs
  TLM/TLM/State/Flags.cs
Labels: COMPATIBILITY
