Repository CitiesSkylinesMods/TMPE, pull requests merged in 2021-08, with the labels that each got.

#1135 Translation update, Indonesian translation added
  TLM/TLM/Resources/Translations/AI_Car.csv
  TLM/TLM/Resources/Translations/AI_Citizen.csv
  TLM/TLM/Resources/Translations/Guide.csv
  TLM/TLM/Resources/Translations/JunctionRestrictions.csv
  TLM/TLM/Resources/Translations/LaneRouting.csv
  TLM/TLM/Resources/Translations/Menu.csv
  TLM/TLM/Resources/Translations/ModConflicts.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/ParkingRestrictions.csv
  TLM/TLM/Resources/Translations/PrioritySigns.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
  TLM/TLM/Resources/Translations/Tutorials.csv
  TLM/TLM/Resources/Translations/VehicleRestrictions.csv
  TLM/TLM/UI/Localization/Translation.cs
Labels: Localisation

#1141 Improved half-segment detection
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: BUG, Usability, UI, regression

#1144 Incomplete vanilla DLC detection fix
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/Util/Shortcuts.cs
Labels: BUG, EXTERNAL

#1142 Incorrect height of vehicle restriction signs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
Labels: BUG, Usability, confirmed, UI, VEHICLE RESTRICTIONS

#1145 Improved pathfinding lifecycle
  TLM/TLM/Custom/PathFinding/CustomPathManager.cs
  TLM/TLM/Lifecycle/Patcher.cs
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/Patch/CustomPathFindPatchAttribute.cs
  TLM/TLM/Patch/_PathFind/CalculatePathPatch.cs
  TLM/TLM/Patch/_PathManager/CreatePathPatch.cs
  TLM/TLM/Patch/_PathManager/ReleasePathPatch.cs
  TLM/TLM/Patch/_PathManager/WaitForAllPathsPatch.cs
  TLM/TLM/TLM.csproj
Labels: BUG, enhancement, confirmed, PATHFINDER, Harmony, lifecycle

#1149 EnumerateSpeedLimits in OnToolGUI ....
  TLM/TLM/State/ConfigData/Main.cs
  TLM/TLM/UI/Helpers/SegmentLaneMarker.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedUnit.cs
Labels: performance

#1150 Simplification - Moved BuildingService methods into ExtBuildingManager.
  TLM/TLM/Manager/Impl/ExtBuildingManager.cs
  TLM/TMPE.CitiesGameBridge/Factory/ServiceFactory.cs
  TLM/TMPE.CitiesGameBridge/Service/BuildingService.cs
  TLM/TMPE.CitiesGameBridge/TMPE.CitiesGameBridge.csproj
  TLM/TMPE.GenericGameBridge/Factory/IServiceFactory.cs
  TLM/TMPE.GenericGameBridge/Service/IBuildingService.cs
  TLM/TMPE.GenericGameBridge/TMPE.GenericGameBridge.csproj
Labels: code cleanup
