Repository CitiesSkylinesMods/TMPE, pull requests merged in 2021-06, with the labels that each got.

#1121 Update locale specific textures on locale change
  TLM/TLM/State/Options.cs
  TLM/TLM/UI/Textures/RoadUI.cs
  TLM/TLM/UI/Textures/TrafficLightTextures.cs
Labels: Localisation

#1118 flag extension
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/ParkingRestrictionsManager.cs
  TLM/TLM/Patch/_PathManager/CreatePathPatch.cs
  TLM/TLM/Patch/_RoadBaseAI/UpdateNodePatch.cs
  TLM/TLM/Patch/_VehicleAI/_AmbulanceAI/StartPathFindPatch.cs
  TLM/TLM/Patch/_VehicleAI/_FireTruckAI/StartPathFindPatch.cs
  TLM/TLM/Patch/_VehicleAI/_PoliceCarAI/StartPathFindPatch.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/ParkingRestrictionsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/Util/Extensions/FlagsExtensions.cs
Labels: performance

#985 Lane connection overlay and performance improvements
  TLM/TLM/UI/Helpers/NodeLaneMarker.cs
  TLM/TLM/UI/Helpers/SegmentLaneMarker.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/Shortcuts.cs
Labels: Accessibility, LANE ROUTING, Overlays, enhancement, in-progress, performance

#1125 Ignore invalid (disconnected) segments while calculating lane routings
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Util/VersionUtil.cs
Labels: BUG, confirmed
