Repository CitiesSkylinesMods/TMPE, pull requests merged in 2022-09, with the labels that each got.

#1645 Train Vehicle Restrictions disabled
  TLM/TLM/Util/Extensions/VehicleExtensions.cs
Labels: confirmed, STABLE, VEHICLE RESTRICTIONS, TEST

#1648 Improved GlobalConfig debug switch values generation
  TLM/TLM/State/ConfigData/DebugSettings.cs
Labels: enhancement, Usability, technical

#1650 What's new in `11.7.0.1`
  CHANGELOG.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: STABLE, meta, TEST

#1660 Refresh tooltip
  TLM/TLM/UI/Helpers/SliderOption.cs
Labels: UI
