Repository CitiesSkylinesMods/TMPE, pull requests merged in 2022-03, with the labels that each got.

#1435 Refactor remainder of `Gameplay` tab
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/OptionsTabs/GameplayTab.cs
  TLM/TLM/State/OptionsTabs/GameplayTab_AIGroups.cs
  TLM/TLM/State/OptionsTabs/GameplayTab_VehicleBehaviourGroup.cs
  TLM/TLM/TLM.csproj
Labels: UI, code cleanup, Settings

#1445 `Shortcuts.ShowErrorDialog` -> `Prompt.Error`
  TLM/TLM/Lifecycle/Patcher.cs
  TLM/TLM/UI/Helpers/Prompt.cs
  TLM/TLM/Util/Shortcuts.cs
  TLM/TLM/Util/VersionUtil.cs
Labels: code cleanup

#1442 nuget UUI
  TLM/TLM/TLM.csproj
  TLM/TLM/packages.config
  TLM/libs/UnifiedUILib.dll
  TLM/libs/UnifiedUILib.dll.mdb
  TLM/libs/UnifiedUILib.xml
Labels: EXTERNAL, meta, API

#1453 hide redudant error when transfering records
  TLM/TLM/Util/Record/TrafficRulesRecord.cs
Labels: Annoyance, serialization

#1443 Tools GUI windows - disable click through UI background
  TLM/TLM/UI/Helpers/Highlight.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: BUG, Usability, confirmed, UI

#1451 Fix wrong texture atlas in scenario editor
  TLM/TLM/State/Keybinds/KeybindUI.cs
  TLM/TLM/U/Panel/BaseUWindowPanel.cs
  TLM/TLM/U/TextureUtil.cs
  TLM/TLM/UI/Helpers/ExtUITabStrip.cs
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/UI/MainMenu/MainMenuWindow.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs
  TLM/TLM/UI/WhatsNew/WhatsNewPanel.cs
Labels: BUG, confirmed, UI, Toolbar, Asset Editor

#1425 Improve mod options lifecycle in editors
  TLM/TLM/Lifecycle/SerializableDataExtension.cs
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/OptionsTabs/MaintenanceTab_FeaturesGroup.cs
Labels: TRAFFIC LIGHTS, Settings, Asset Editor

#1454 Read elevation keybind from vanilla settings
  TLM/TLM/State/Keybinds/KeybindSetting.cs
  TLM/TLM/State/Keybinds/KeybindSettingsBase.cs
  TLM/TLM/State/Keybinds/KeybindSettingsPage.cs
  TLM/TLM/State/Keybinds/KeybindUI.cs
  TLM/TLM/U/UIUtil.cs
  TLM/TLM/UI/Localization/LookupTable.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TMPE.UnitTest/TMPE.UnitTest.csproj
  TLM/TMPE.UnitTest/Util/DynamicKeybindReplaceTest.cs
Labels: Usability, Keybinds

#1456 Update harmony id
  TLM/TLM/Custom/PathFinding/CustomPathManager.cs
  TLM/TLM/Lifecycle/Patcher.cs
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/State/GlobalConfig.cs
  TLM/TMPE.API/Harmony.cs
  TLM/TMPE.API/TMPE.API.csproj
Labels: meta, API, Settings, Harmony

#1444 Despwan tool tweaks
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/Util/Extensions/VehicleExtensions.cs
Labels: code cleanup

#1441 Vehicle type exclusion list for "Disable despawning" feature
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Patch/PatchCommons.cs
  TLM/TLM/Patch/_External/RTramAIModPatch.cs
  TLM/TLM/Patch/_VehicleAI/_CarAI/SimulationStepPatch.cs
  TLM/TLM/State/ConfigData/Gameplay.cs
  TLM/TLM/State/OptionsTabs/GameplayTab_VehicleBehaviourGroup.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/AllowDespawn/AllowDespawnPanel.cs
  TLM/TLM/UI/Helpers/GlobalConfigObserver.cs
  TLM/TLM/UI/MainMenu/DespawnButton.cs
  TLM/TLM/Util/Extensions/FlagsExtensions.cs
Labels: feature, DESPAWN TOOLS

#1457 use harmony prepare instead of manual patch
  TLM/TLM/Lifecycle/Patcher.cs
  TLM/TLM/Patch/_External/RTramAIModPatch.cs
Labels: EXTERNAL, Harmony

#1455 Refactor remainder of `Policies` tab groups
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/GameplayTab_VehicleBehaviourGroup.cs
  TLM/TLM/State/OptionsTabs/OptionsMassEditTab.cs
  TLM/TLM/State/OptionsTabs/PoliciesTab.cs
  TLM/TLM/State/OptionsTabs/PoliciesTab_InEmergenciesGroup.cs
  TLM/TLM/State/OptionsTabs/PoliciesTab_OnHighwaysGroup.cs
  TLM/TLM/State/OptionsTabs/PoliciesTab_OnRoadsGroup.cs
  TLM/TLM/State/OptionsTabs/PoliciesTab_PriorityRoadsGroup.cs
  TLM/TLM/State/OptionsTabs/PoliciesTab_RoundaboutsGroup.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Util/PriorityRoad.cs
  TLM/TLM/Util/RoundaboutMassEdit.cs
Labels: UI, code cleanup, Settings

#1463 Un-invert `Options.disableDespawning` data byte
  TLM/TLM/Lifecycle/SerializableDataExtension.cs
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Configuration.cs
  TLM/TLM/State/OptionsTabs/GameplayTab_VehicleBehaviourGroup.cs
Labels: code cleanup, Settings

#1464 Ensure defaults set correctly - fix regressions
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Options.cs
Labels: Settings, regression

#1433 What's New in TM:PE 11.6.5.1 ?
  CHANGELOG.md
  README.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
  TLM/TLM/Util/VersionUtil.cs
Labels: meta

#1465 Hotfix for 11.6.5.1 before release
  CHANGELOG.md
  README.md
  TLM/TLM/Lifecycle/SerializableDataExtension.cs
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/Localization/LookupTable.cs
  TLM/TLM/UI/MainMenu/DespawnButton.cs
Labels: BUG

#1471 fix regression for reversible tram patch
  TLM/TLM/Lifecycle/Patcher.cs
  TLM/TLM/Patch/_External/RTramAIModPatch.cs
  TLM/TLM/Util/ModsCompatibilityChecker.cs
Labels: BUG, EXTERNAL, Harmony

#1211 uni-directional lane connections
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManagerData/ConnectionDataBase.cs
  TLM/TLM/Manager/Impl/LaneConnectionManagerData/LaneConnectionData.cs
  TLM/TLM/Manager/Impl/LaneConnectionManagerData/LaneEnd.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/State/Configuration.cs
  TLM/TLM/State/Flags.cs
  TLM/TLM/State/SerializationUtil.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/Extensions/ArrayExtensions.cs
  TLM/TLM/Util/Extensions/NetLaneExtensions.cs
  TLM/TLM/Util/Extensions/NetSegmentExtensions.cs
  TLM/TLM/Util/SeparateTurningLanesUtil.cs
Labels: BUG, LANE ROUTING

#1477 address warnings in Routing manager
  TLM/.editorconfig
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/State/Flags.cs
Labels: code cleanup, Blocking

#1483 trains prefer to stay in lane at all intersections
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Util/Extensions/FlagsExtensions.cs
  TLM/TLM/Util/TrackUtils.cs
Labels: BUG, LANE ROUTING

#1467 Train tracks segment speed limits
  TLM/.editorconfig
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/Manager/Impl/SpeedLimitManagerExt.cs
  TLM/TLM/UI/SubTools/SpeedLimits/Overlay/OverlaySegmentSpeedlimitHandle.cs
  TLM/TLM/UI/SubTools/SpeedLimits/Overlay/SpeedLimitsOverlay.cs
  TLM/TLM/Util/Extensions/NetSegmentExtensions.cs
  TLM/TLM/Util/RoundaboutMassEdit.cs
  TLM/TLM/Util/Shortcuts.cs
  TLM/TMPE.API/Traffic/Data/SpeedValue.cs
Labels: BUG, SPEED LIMITS, regression

#1490 Modernise several uses of `GetSortedLanes()`
  TLM/TLM/Manager/Impl/LaneArrowManager.cs
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/Overlay/OverlayLaneSpeedlimitHandle.cs
  TLM/TLM/Util/Extensions/NetSegmentExtensions.cs
  TLM/TLM/Util/SegmentLaneTraverser.cs
Labels: code cleanup

#1491 hollow floating wire
  TLM/TLM/Resources/LaneConnectionManager/add_cursor.png
  TLM/TLM/Resources/LaneConnectionManager/remove_cursor.png
  TLM/TLM/TLM.csproj
  TLM/TLM/U/CursorUtil.cs
  TLM/TLM/UI/LegacySubTool.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: Usability, UI, DO NOT MERGE YET, LANE ROUTING

#1492 bidirectional lane connection UI
  TLM/.editorconfig
  TLM/TLM/Resources/LaneConnectionManager/direction_arrow.png
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/Helpers/Highlight.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/TMPEVectorUtil.cs
Labels: UI, LANE ROUTING
