Repository CitiesSkylinesMods/TMPE, pull requests merged in 2022-07, with the labels that each got.

#1607 TTL quick setup phase 2
  TLM/TLM/UI/SubTools/TTL/TimedTrafficLightsTool.cs
  TLM/TLM/Util/AutoTimedTrafficLights.cs
  TLM/TLM/Util/SeparateTurningLanesUtil.cs
Labels: TRAFFIC LIGHTS, Pedestiran Crossing

#1610 calculate gap for pedestrian crossing dynamically
  TLM/TLM/Patch/_CitizenAI/GetPathTargetPositionPatch.cs
  TLM/TLM/TLM.csproj
Labels: Pedestiran Crossing

#1611 Fix incorrect target method for harmony patches
  TLM/TLM/Patch/_RoadBaseAI/TrafficLightSimulationStepPatch.cs
  TLM/TLM/Patch/_TrainTrackBaseAI/LevelCrossingSimulationStepPatch.cs
Labels: BUG, TRAFFIC LIGHTS, Harmony

#1617 Loading TM:PE data failed - notify the user
  TLM/TLM/Lifecycle/SerializableDataExtension.cs
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/State/Keybinds/KeybindSettingsBase.cs
  TLM/TLM/Util/Extensions/VehicleExtensions.cs
Labels: BUG, UI, code cleanup, serialization

#1575 What's New - TM:PE 11.6.6.0
  CHANGELOG.md
  TLM/SharedAssemblyInfo.cs
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: meta

#1621 `InvalidOperationException` saving lane connection data
  TLM/TLM/Manager/Impl/LaneConnection/LaneConnectionSubManager.cs
Labels: BUG, confirmed, LANE ROUTING

#1619 Infinite loop while traversing segments of node
  TLM/TLM/Util/Iterators/GetNodeSegmentIdsEnumerator.cs
Labels: BUG, confirmed, SPEED LIMITS, Overlays

#1623 What's New - TM:PE 11.6.6.1
  CHANGELOG.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: meta
