Repository CitiesSkylinesMods/TMPE, pull requests merged in 2022-08, with the labels that each got.

#1625 TMPE settings not applied immediately after loading the savegame
  TLM/TLM/Lifecycle/SerializableDataExtension.cs
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/packages.config
Labels: BUG, confirmed, STABLE, Harmony, serialization, TEST

#1627 What's new update for 11.6.6.2
  CHANGELOG.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: meta

#1628 Lane connections not removed when segment has been released
  TLM/TLM/Manager/Impl/LaneConnection/LaneConnectionSubManager.cs
Labels: confirmed, STABLE, LANE ROUTING, regression, TEST

#1629 What's new changelog update
  CHANGELOG.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: meta

#1631 Changelogs update - stable release
  CHANGELOG.md
  TLM/TLM/Resources/whats_new.txt
Labels: STABLE, meta

#1615 lane connection code cleanup
  TLM/.editorconfig
  TLM/TLM/Manager/Impl/LaneConnection/LaneConnectionSubManager.cs
  TLM/TLM/UI/Helpers/Highlight.cs
  TLM/TLM/UI/Helpers/SegmentLaneMarker.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/RoutingDetector/LaneEnd.cs
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: code cleanup, Blocking
