Repository CitiesSkylinesMods/TMPE, pull requests merged in 2022-01, with the labels that each got.

#1265 Static texture classes are now proper CustomManagers
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs
  TLM/TLM/UI/Helpers/TrafficRulesOverlay.cs
  TLM/TLM/UI/ModUI.cs
  TLM/TLM/UI/SubTools/ManualTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/PrioritySigns/PrioritySignsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/Overlay/SignRenderer.cs
  TLM/TLM/UI/SubTools/SpeedLimits/Overlay/SpeedLimitsOverlay.cs
  TLM/TLM/UI/SubTools/TimedTrafficLights/TimedTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/ToggleTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/UI/Textures/JunctionRestrictions.cs
  TLM/TLM/UI/Textures/RoadSignThemes.cs
  TLM/TLM/UI/Textures/RoadUI.cs
  TLM/TLM/UI/Textures/TrafficLightTextures.cs
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: technical, UI, Overlays

#1273 Netutil cleanup
  TLM/Benchmarks/GetNodeSegmentIdsEnumerablePerfTests.cs
  TLM/Benchmarks/GetSegmentLaneIdAndSegmentPerfTests.cs
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/Manager/AbstractGeometryObservingManager.cs
  TLM/TLM/Manager/Impl/ExtNodeManager.cs
  TLM/TLM/Manager/Impl/ExtPathManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentManager.cs
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/GeometryNotifier.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Notifier.cs
  TLM/TLM/Patch/_CitizenAI/_HumanAI/CheckTrafficLightsPatch.cs
  TLM/TLM/Patch/_RoadBaseAI/ClickNodeButtonPatch.cs
  TLM/TLM/Patch/_RoadBaseAI/UpdateLanesPatch.cs
  TLM/TLM/Patch/_VehicleAI/UpdatePathTargetPositionsPatch.cs
  TLM/TLM/Patch/_VehicleAI/VehicleAICommons.cs
  TLM/TLM/Patch/_VehicleAI/_CarAI/CalculateSegmentPositionPatch.cs
  TLM/TLM/Patch/_VehicleAI/_CarAI/CalculateSegmentPositionPatch2.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/GetLocalizedStatusPatch.cs
  TLM/TLM/Patch/_VehicleAI/_TrainAI/CheckNextLanePatch.cs
  TLM/TLM/Patch/_VehicleAI/_TrainAI/ForceTrafficLightsPatch.cs
  TLM/TLM/Patch/_VehicleAI/_TrainAI/SimulationStep2Patch.cs
  TLM/TLM/Patch/_VehicleAI/_TramBaseAI/CalculateSegmentPositionPatch2.cs
  TLM/TLM/State/Asset/SegmentNetworkIDs.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/TrafficLight/Impl/CustomSegmentLights.cs
  TLM/TLM/UI/Helpers/Highlight.cs
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/UI/SubTools/ManualTrafficLightsTool.cs
  TLM/TLM/UI/SubTools/SpeedLimits/Overlay/OverlayLaneSpeedlimitHandle.cs
  TLM/TLM/UI/SubTools/SpeedLimits/Overlay/OverlaySegmentSpeedlimitHandle.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/AutoTimedTrafficLights.cs
  TLM/TLM/Util/Extensions/BuildingExtensions.cs
  TLM/TLM/Util/Extensions/CitizenInstanceExtensions.cs
  TLM/TLM/Util/Extensions/NetLaneExtensions.cs
  TLM/TLM/Util/Extensions/NetNodeExtensions.cs
  TLM/TLM/Util/Extensions/NetSegmentExtensions.cs
  TLM/TLM/Util/GeometryUtil.cs
  TLM/TLM/Util/Iterators/GetNodeSegmentIdsEnumerable.cs
  TLM/TLM/Util/Iterators/GetNodeSegmentIdsEnumerator.cs
  TLM/TLM/Util/Iterators/GetSegmentLaneIdsEnumerable.cs
  TLM/TLM/Util/Iterators/GetSegmentLaneIdsEnumerator.cs
  TLM/TLM/Util/LaneUtil.cs
  TLM/TLM/Util/PlaceIntersectionUtil.cs
  TLM/TLM/Util/PriorityRoad.cs
  TLM/TLM/Util/Record/LaneArrowsRecord.cs
  TLM/TLM/Util/Record/LaneConnectionRecord.cs
  TLM/TLM/Util/Record/NodeRecord.cs
  TLM/TLM/Util/Record/SegmentRecord.cs
  TLM/TLM/Util/Record/SpeedLimitLaneRecord.cs
  TLM/TLM/Util/Record/TrafficRulesRecord.cs
  TLM/TLM/Util/Record/VehicleRestrictionsLaneRecord.cs
  TLM/TLM/Util/RoundaboutMassEdit.cs
  TLM/TLM/Util/SegmentLaneTraverser.cs
  TLM/TLM/Util/SeparateTurningLanesUtil.cs
  TLM/TLM/Util/Shortcuts.cs
  TLM/TMPE.UnitTest/Util/GetNodeSegmentIdsEnumerableTests.cs
Labels: code cleanup

#1275 Sl-cleanup
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/Manager/Impl/TrafficMeasurementManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Patch/_VehicleAI/VehicleAICommons.cs
  TLM/TLM/Patch/_VehicleAI/_TrolleybusAI/CalculateSegmentPositionPatch.cs
  TLM/TLM/UI/SubTools/SpeedLimits/Overlay/SpeedLimitsOverlay.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/LaneUtil.cs
  TLM/TLM/Util/Record/SpeedLimitLaneRecord.cs
  TLM/TLM/Util/RoundaboutMassEdit.cs
  TLM/TMPE.API/Manager/ISpeedLimitManager.cs
Labels: code cleanup, SPEED LIMITS

#1281 versioned atlas
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/U/AtlasBuilder.cs
  TLM/TLM/U/Button/UButton.cs
  TLM/TLM/U/TextureUtil.cs
  TLM/TLM/UI/MainMenu/MainMenuWindow.OsdPanel.cs
  TLM/TLM/UI/MainMenu/MainMenuWindow.ToolPanel.cs
  TLM/TLM/UI/RemoveCitizenInstanceButtonExtender.cs
  TLM/TLM/UI/RemoveVehicleButtonExtender.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowToolWindow.cs
  TLM/TLM/Util/Extensions/VersionExtension.cs
Labels: UI, lifecycle

#1287 Add 2 Traffic++ v2 mods to incompatible list
  TLM/TLM/Resources/incompatible_mods.txt
Labels: EXTERNAL, COMPATIBILITY

#1285 Slm data rework hotfix
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
Labels: SPEED LIMITS

#1286 Better AssetEditor mode detection
  TLM/TLM/Lifecycle/TMPELifecycle.cs
Labels: BUG, confirmed, Asset Editor

#1277 Slm data rework
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/UI/SubTools/SpeedLimits/Overlay/SpeedLimitsOverlay.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsTool.cs
  TLM/TMPE.API/Manager/ISpeedLimitManager.cs
Labels: code cleanup, SPEED LIMITS

#1290 Play mode detection improvement
  TLM/TLM/Lifecycle/TMPELifecycle.cs
Labels: confirmed, Asset Editor, regression

#1284 What's New panel
  TLM/SharedAssemblyInfo.cs
  TLM/TLM/Lifecycle/SerializableDataExtension.cs
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/State/ConfigData/Main.cs
  TLM/TLM/State/Configuration.cs
  TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs
  TLM/TLM/State/VersionInfo.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/ModUI.cs
  TLM/TLM/UI/WhatsNew/MarkupKeyword.cs
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
  TLM/TLM/UI/WhatsNew/WhatsNewMarkup.cs
  TLM/TLM/UI/WhatsNew/WhatsNewPanel.cs
  TLM/TLM/Util/VersionUtil.cs
Labels: feature, high priority, Usability, UI, Settings

#1293 Readme 11.6.3
  README.md
Labels: meta

#1292 Changelog v11.6.3
  CHANGELOG.md
Labels: meta

#1296 Reduce loading log spam from AssetDataExtension
  TLM/TLM/Lifecycle/AssetDataExtension.cs
Labels: Annoyance, Asset Editor

#1303 TM:PE settings not copy pasted in-game
  TLM/TLM/Lifecycle/ThreadingExtension.cs
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/State/TMPEMoveITIntegration.cs
  TLM/TLM/Util/Record/SpeedLimitLaneRecord.cs
Labels: BUG, confirmed, SPEED LIMITS, Asset Editor

#1304 Update localization files
  TLM/TLM/Resources/Translations/Guide.csv
  TLM/TLM/Resources/Translations/LaneRouting.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
Labels: Localisation

#1306 General tab - redux
  TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs
Labels: Usability, UI, Settings

#1308 Place Intersection improvements, bugfixing
  TLM/TLM/Patch/_BuildingDecoration/LoadPathsPatch.cs
  TLM/TLM/Util/PlaceIntersectionUtil.cs
Labels: BUG, EXTERNAL, Asset Editor

#1310 Fix game version warning
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/Util/ModsCompatibilityChecker.cs
  TLM/TLM/Util/VersionUtil.cs
Labels: UI, COMPATIBILITY

#1305 11.6.4 What's New
  CHANGELOG.md
  README.md
  TLM/SharedAssemblyInfo.cs
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/Patch/_CitizenAI/_TouristAI/Connection/TouristAIConnection.cs
  TLM/TLM/Patch/_CitizenAI/_TouristAI/GetVehicleInfoPatch.cs
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
  TLM/TLM/Util/VersionUtil.cs
Labels: meta

#1318 Speed limit overlay signs not visible on train tracks
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
Labels: LABS, STABLE, SPEED LIMITS, regression

#1319 Refactor `WhatsNew.cs` and update the UI
  TLM/TLM/UI/WhatsNew/MarkupKeyword.cs
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
  TLM/TLM/UI/WhatsNew/WhatsNewMarkup.cs
  TLM/TLM/UI/WhatsNew/WhatsNewPanel.cs
Labels: UI, code cleanup

#1317 What's New 11.6.4.1
  CHANGELOG.md
  README.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: meta

#1323 Fix metro track detection - Speed Limits overlays
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
Labels: BUG, confirmed, SPEED LIMITS, regression

#1328 Update changelogs, bump WN version
  CHANGELOG.md
  README.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: docs, STABLE, TEST

#1321 Refactor OptionsManager.cs
  TLM/TLM/Manager/Impl/OptionsManager.cs
Labels: code cleanup, Blocking

#1335 Show full `What's New` version in UI
  TLM/TLM/Lifecycle/TrafficManagerMod.cs
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
  TLM/TLM/Util/VersionUtil.cs
Labels: enhancement

#1331 Incorrect minimal number of path-find threads
  TLM/TLM/Custom/PathFinding/CustomPathManager.cs
Labels: BUG, confirmed, STABLE, PATHFINDER, TEST

#1336 Disable `What's New` on TM:PE button
  TLM/TLM/UI/ModUI.cs
Labels: BUG, STABLE, UI, TEST

#1332 What's New in TM:PE 11.6.4.3?
  CHANGELOG.md
  README.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: meta
