Repository CitiesSkylinesMods/TMPE, pull requests merged in 2022-02, with the labels that each got.

#1341 Filtered despawn
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/OptionsMaintenanceTab.cs
  TLM/TLM/State/OptionsTabs/OptionsMaintenanceTab_DespawnGroup.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/Localization/LookupTable.cs
  TLM/TLM/Util/Extensions/VehicleExtensions.cs
Labels: enhancement, Localisation, DESPAWN TOOLS, Settings

#1338 Aircraft pathfinding fix
  TLM/TLM/Custom/PathFinding/CustomPathManager.cs
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Patch/_PathManager/CreatePathPatch.cs
Labels: BUG, STABLE, PATHFINDER, Vehicle Behavior, TEST

#1333 Modify how info views affect TM:PE
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: Usability, UI, Toolbar

#1343 Pathfinder update despawner
  TLM/TLM/Custom/PathFinding/PathfinderUpdates.cs
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/TLM.csproj
Labels: UI, PATHFINDER, lifecycle, Vehicle Behavior

#1339 What's new in 11.6.4.4?
  CHANGELOG.md
  README.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: meta

#1345 Catch + log any load/save errors in `OptionsManager`
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Options.cs
Labels: high priority, technical, Settings

#1348 `Log.Warning()` -> `Log.Info()` for missing localised image resources
  TLM/TLM/UI/Localization/Translation.cs
Labels: Annoyance, Localisation

#1350 ` ReplaceMaxPosTranspiler`: `Log.Warning()` -> `Log.Info()`
  TLM/TLM/Patch/_VehicleAI/StartPathFindCommons.cs
Labels: Annoyance, Harmony

#1347 Revise warning that was confusing users
  TLM/TLM/Custom/PathFinding/PathfinderUpdates.cs
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/UI/Helpers/Prompt.cs
Labels: high priority, Usability

#1351 What's New in TM:PE 11.6.4.5 ?
  CHANGELOG.md
  README.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: meta

#1360 Update CSM (Cities Skylines Multiplayer) mod detection
  TLM/TLM/Resources/incompatible_mods.txt
  TLM/TLM/Util/ModsCompatibilityChecker.cs
Labels: EXTERNAL, COMPATIBILITY

#1357 CSUR: Lane connectors on transition segments not available
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
Labels: BUG, confirmed, EXTERNAL, LANE ROUTING, COMPATIBILITY

#1301 Extend `CheckboxOption` with new properties
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs
  TLM/TLM/State/OptionsTabs/OptionsGeneralTab_DebugCheckbox.cs
  TLM/TLM/State/OptionsTabs/OptionsMaintenanceTab_DespawnGroup.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/Helpers/CheckboxOption.cs
  TLM/TLM/UI/Helpers/SerializableUIOptionBase.cs
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: technical, UI, Settings

#1358 What's New in TM:PE 11.6.4.6?
  CHANGELOG.md
  README.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: meta

#1362 Fix `GetVanillaNetInfoSpeedLimit()` to only inspect customisable lanes
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
Labels: BUG, high priority, STABLE, SPEED LIMITS, Overlays, MASS EDIT, TEST

#1364 Fix `SPEED_TO_MPH` value in `ApiConstants.cs`
  TLM/TLM/Constants.cs
  TLM/TMPE.API/Traffic/ApiConstants.cs
Labels: BUG, high priority, confirmed, STABLE, SPEED LIMITS, TEST

#1367 Remove old speed constants
  TLM/TLM/Constants.cs
  TLM/TMPE.API/Traffic/ApiConstants.cs
Labels: code cleanup

#1365 What's New in TM:PE 11.6.4.7 ?
  CHANGELOG.md
  README.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: meta

#1381 Allow vehicles to use restricted lanes when spawning or arriving at destination
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
Labels: VEHICLE RESTRICTIONS, PATHFINDER

#1389 Mark known and potential `MALWARE` mods as incompatible
  TLM/TLM/Resources/incompatible_mods.txt
  TLM/TLM/Util/ModsCompatibilityChecker.cs
Labels: EXTERNAL, COMPATIBILITY

#1382 What's New in TM:PE 11.6.4.8 ?
  CHANGELOG.md
  README.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: meta

#1371 Rename `OptionsVehicleRestrictionsTab` -> `PoliciesTab`
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/LaneArrowManager.cs
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/Patch/_RoadBaseAI/UpdateLanesPatch.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/OptionsMaintenanceTab.cs
  TLM/TLM/State/OptionsTabs/PoliciesTab.cs
  TLM/TLM/TLM.csproj
Labels: code cleanup, Settings

#1370 Rename `OptionsGameplayTab` -> `GameplayTab`
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/GameplayTab.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/MainMenu/DespawnButton.cs
Labels: code cleanup, Settings

#1369 Rename `OptionsGeneralTab` -> `GeneralTab`
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/GeneralTab.cs
  TLM/TLM/State/OptionsTabs/GeneralTab_DebugGroup.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/IncompatibleModsPanel.cs
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsToolWindow.MphToggleButton.cs
Labels: code cleanup, Settings

#1396 Converted almost all m_lanes.m_buffer[laneId] calls to laneId.ToLane()
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
  TLM/TLM/Manager/Impl/ExtSegmentManager.cs
  TLM/TLM/Manager/Impl/LaneArrowManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/SpeedLimitManager.cs
  TLM/TLM/Manager/Impl/TrafficMeasurementManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/Patch/_VehicleAI/UpdatePathTargetPositionsPatch.cs
  TLM/TLM/Patch/_VehicleAI/VehicleAICommons.cs
  TLM/TLM/Patch/_VehicleAI/_CarAI/CalculateSegmentPositionPatch2.cs
  TLM/TLM/Patch/_VehicleAI/_TrainAI/CheckNextLanePatch.cs
  TLM/TLM/Patch/_VehicleAI/_TrainAI/ForceTrafficLightsPatch.cs
  TLM/TLM/Patch/_VehicleAI/_TrainAI/SimulationStep2Patch.cs
  TLM/TLM/Patch/_VehicleAI/_TramBaseAI/CalculateSegmentPositionPatch2.cs
  TLM/TLM/State/Flags.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowButton.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/ParkingRestrictionsTool.cs
  TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/GeometryUtil.cs
Labels: code cleanup

#1397 Converted all Singleton<CitizenManager>.instance.m_citizens.m_buffer[…
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Patch/_CitizenAI/_HumanAI/ArriveAtDestinationPatch.cs
  TLM/TLM/Patch/_CitizenAI/_HumanAI/SimulationStepPatch.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/UpdateParkedVehiclePatch.cs
  TLM/TLM/UI/RemoveCitizenInstanceButtonExtender.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/Extensions/CitizenExtensions.cs
Labels: code cleanup

#1398 Moved IsMiddle to NetNodeExtensions and some cleanup where it is used.
  TLM/TLM/UI/Helpers/Highlight.cs
  TLM/TLM/Util/Extensions/NetNodeExtensions.cs
Labels: code cleanup

#1393 What's new - StackoverflowException fix attempt
  TLM/TLM/UI/ModUI.cs
  TLM/TLM/UI/WhatsNew/WhatsNewPanel.cs
Labels: STABLE, UI, TEST

#1391 Update support policy
  README.md
Labels: meta

#1390 Update incompatible_mods.txt
  TLM/TLM/Resources/incompatible_mods.txt
Labels: COMPATIBILITY

#1399 ToCitizenUnit via extension methods.
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/ParkVehiclePatch.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Util/Extensions/CitizenUnitExtensions.cs
Labels: code cleanup

#1386 Add Patcher manual patch. Add patch for Reversible Tram AI mod
  TLM/TLM/Lifecycle/Patcher.cs
  TLM/TLM/Patch/_External/RTramAIModPatch.cs
  TLM/TLM/TLM.csproj
Labels: COMPATIBILITY, Vehicle Behavior

#1373 Rename `OptionsOverlaysTab` -> `OverlaysTab`
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/OptionsMaintenanceTab.cs
  TLM/TLM/State/OptionsTabs/OverlaysTab.cs
  TLM/TLM/State/OptionsTabs/PoliciesTab.cs
  TLM/TLM/TLM.csproj
Labels: code cleanup, Settings

#1401 More use of ToCitizen() extension method.
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Patch/_CitizenAI/_HumanAI/SimulationStepPatch.cs
  TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs
  TLM/TLM/Patch/_CitizenAI/_TouristAI/GetVehicleInfoPatch.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/GetLocalizedStatusPatch.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/ParkVehiclePatch.cs
Labels: code cleanup

#1400 More of the same - ToCitizenInstance
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Patch/_VehicleAI/_CarAI/SimulationStepPatch.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/GetLocalizedStatusPatch.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/ParkVehiclePatch.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/StartPathFindPatch.cs
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/UI/RemoveCitizenInstanceButtonExtender.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/Extensions/CitizenInstanceExtensions.cs
Labels: code cleanup

#1406 Removed now trivial ExtCitizenInstanceManager.GetCitizenId(ushort ins…
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TMPE.API/Manager/IExtCitizenInstanceManager.cs
Labels: code cleanup

#1403 Rename `OptionsMaintenanceTab` -> `MaintenanceTab`
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/MaintenanceTab.cs
  TLM/TLM/State/OptionsTabs/MaintenanceTab_DespawnGroup.cs
  TLM/TLM/State/OptionsTabs/PoliciesTab.cs
  TLM/TLM/TLM.csproj
Labels: code cleanup, Settings

#1404 Themed default speed signs (redux)
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/OverlaysTab.cs
  TLM/TLM/UI/SubTools/SpeedLimits/Overlay/SignRenderer.cs
  TLM/TLM/UI/SubTools/SpeedLimits/Overlay/SpeedLimitsOverlay.cs
Labels: Usability, Localisation, UI, SPEED LIMITS, Overlays, Settings

#1408 Skip searching for best emergency lane for non-car vehicles
  TLM/TLM/Patch/_VehicleAI/UpdatePathTargetPositionsPatch.cs
Labels: STABLE, PATHFINDER, DLS, TEST

#1407 Refactoring/parked vehicles extensions
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/Patch/_CitizenAI/_HumanAI/SimulationStepPatch.cs
  TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs
  TLM/TLM/Patch/_CitizenAI/_TouristAI/GetVehicleInfoPatch.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/Extensions/FlagsExtensions.cs
  TLM/TLM/Util/Extensions/ParkedVehicleExtensions.cs
Labels: code cleanup

#1378 Add options API
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/Options.cs
  TLM/TMPE.API/Manager/IOptionsManager.cs
Labels: API, Settings

#1415 Update translations
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
Labels: Localisation, UI, TRAFFIC LIGHTS, SPEED LIMITS, Settings

#1413 Converted all calls from Singleton<VehicleManager>.instance.m_vehicle…
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/TrafficPriorityManager.cs
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/Patch/_CitizenAI/_HumanAI/SimulationStepPatch.cs
  TLM/TLM/Patch/_PathManager/CreatePathPatch.cs
  TLM/TLM/Patch/_VehicleAI/_CarAI/SimulationStepPatch.cs
  TLM/TLM/Patch/_VehicleAI/_TrainAI/CheckNextLanePatch.cs
  TLM/TLM/Patch/_VehicleAI/_TrainAI/SimulationStep2Patch.cs
  TLM/TLM/Patch/_VehicleManager/CreateVehiclePatch.cs
  TLM/TLM/Patch/_VehicleManager/ReleaseVehiclePatch.cs
  TLM/TLM/Traffic/Impl/SegmentEnd.cs
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/Extensions/VehicleExtensions.cs
Labels: code cleanup

#1417 Update LICENSE
  LICENSE
  TLM/SharedAssemblyInfo.cs
  TLM/TLM/Properties/AssemblyInfo.cs
  TLM/TMPE.API/Properties/AssemblyInfo.cs
Labels: docs, meta

#1402 What's New in TM:PE 11.6.5.0 TEST?
  CHANGELOG.md
  README.md
  TLM/SharedAssemblyInfo.cs
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
  TLM/TLM/Util/VersionUtil.cs
Labels: meta

#1418 Update github pages index
  docs/index.md
Labels: docs, meta

#1424 Add button classes for use in mod options
  TLM/TLM/State/ConfigData/Main.cs
  TLM/TLM/State/GlobalConfig.cs
  TLM/TLM/State/OptionsTabs/GeneralTab.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/Helpers/ActionButton.cs
  TLM/TLM/UI/Helpers/OptionButtonBase.cs
  TLM/TLM/UI/Helpers/UrlButton.cs
Labels: docs, UI, Settings, Blocking

#1419 Update `CheckboxOption`
  TLM/TLM/State/OptionsTabs/GeneralTab_DebugGroup.cs
  TLM/TLM/UI/Helpers/CheckboxOption.cs
  TLM/TLM/UI/Helpers/SerializableUIOptionBase.cs
Labels: Usability, UI, Settings, Blocking

#1430 Minor update to checkboxes
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/GameplayTab.cs
  TLM/TLM/State/OptionsTabs/GeneralTab.cs
  TLM/TLM/State/OptionsTabs/MaintenanceTab.cs
  TLM/TLM/State/OptionsTabs/PoliciesTab.cs
  TLM/TLM/UI/Helpers/CheckboxOption.cs
Labels: code cleanup, Settings, Blocking

#1416 Split some options in to `GameplayTab_VehicleBehaviourGroup`
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/State/OptionsTabs/GameplayTab.cs
  TLM/TLM/State/OptionsTabs/GameplayTab_VehicleBehaviourGroup.cs
  TLM/TLM/State/OptionsTabs/MaintenanceTab_DespawnGroup.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/MainMenu/DespawnButton.cs
Labels: code cleanup, Settings

#1411 Split some options in to `GeneralTab_LocalisationGroup`
  TLM/TLM/State/OptionsTabs/GeneralTab.cs
  TLM/TLM/State/OptionsTabs/GeneralTab_LocalisationGroup.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/SubTools/SpeedLimits/SpeedLimitsToolWindow.MphToggleButton.cs
Labels: code cleanup, Settings

#1431 Add slider option UI component
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/Helpers/CheckboxOption.cs
  TLM/TLM/UI/Helpers/SerializableUIOptionBase.cs
  TLM/TLM/UI/Helpers/SliderOption.cs
Labels: UI, Settings, Blocking

#1436 Remove gamebridge stuff from TLM.csproj build script
  TLM/TLM/TLM.csproj
Labels: code cleanup

#1432 Refactor remainder of `General` tab
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/Manager/Impl/JunctionRestrictionsManager.cs
  TLM/TLM/Manager/Impl/LaneArrowManager.cs
  TLM/TLM/Manager/Impl/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/OptionsManager.cs
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/State/ConfigData/Main.cs
  TLM/TLM/State/GlobalConfig.cs
  TLM/TLM/State/Options.cs
  TLM/TLM/State/OptionsTabs/GeneralTab.cs
  TLM/TLM/State/OptionsTabs/GeneralTab_CompatibilityGroup.cs
  TLM/TLM/State/OptionsTabs/GeneralTab_DebugGroup.cs
  TLM/TLM/State/OptionsTabs/GeneralTab_InterfaceGroup.cs
  TLM/TLM/State/OptionsTabs/GeneralTab_LocalisationGroup.cs
  TLM/TLM/State/OptionsTabs/GeneralTab_SimulationGroup.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/U/UOpacityValue.cs
  TLM/TLM/UI/IncompatibleModsPanel.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TMPE.API/Manager/IOptionsManager.cs
Labels: Usability, UI, code cleanup, Settings

#1440 Fix typo: `Mofied` -> `Modified`
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Notifier.cs
Labels: code cleanup
