Repository CitiesSkylinesMods/TMPE, pull requests merged in 2022-06, with the labels that each got.

#1576 Release 11.6.5.3
  CHANGELOG.md
  TLM/TLM/Lifecycle/TMPELifecycle.cs
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/State/Keybinds/KeybindUI.cs
  TLM/TLM/State/OptionsTabs/GameplayTab_AIGroups.cs
  TLM/TLM/State/OptionsTabs/GeneralTab_LocalisationGroup.cs
  TLM/TLM/State/OptionsTabs/GeneralTab_SimulationGroup.cs
  TLM/TLM/UI/Helpers/DropDownOption.cs
  TLM/TLM/UI/Helpers/SerializableUIOptionBase.cs
  TLM/TLM/UI/Helpers/SliderOption.cs
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: STABLE, meta, TEST

#1565 redundant transitions
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Util/TrackUtils.cs
Labels: BUG, LANE ROUTING

#1581 DLS incorrectly calculates 'max unsafe speed difference' value
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
Labels: BUG, DLS

#1594 Fix broken hovered element detection after hovering invalid element
  TLM/TLM/UI/TrafficManagerTool.cs
Labels: STABLE, LANE ROUTING, regression, TEST

#1584 Declutter logging in RecalculateLaneEndRoutingData
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/Util/DetailLogger.cs
Labels: code cleanup

#1550 separete lane connections for track/road vehicles.
  TLM/TLM/Manager/Impl/ExtNodeManager.cs
  TLM/TLM/Manager/Impl/LaneConnection/LaneConnectionManager.cs
  TLM/TLM/Manager/Impl/LaneConnection/LaneConnectionSubManager.cs
  TLM/TLM/Manager/Impl/RoutingManager.cs
  TLM/TLM/Resources/LaneConnectionManager/direction_arrow.png
  TLM/TLM/State/Configuration.cs
  TLM/TLM/State/Flags.cs
  TLM/TLM/UI/Helpers/Highlight.cs
  TLM/TLM/UI/Helpers/NodeLaneMarker.cs
  TLM/TLM/UI/Helpers/SegmentLaneMarker.cs
  TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
  TLM/TLM/UI/SubTools/RoutingDetector/LaneEnd.cs
  TLM/TLM/Util/Record/LaneConnectionRecord.cs
  TLM/TLM/Util/SeparateTurningLanesUtil.cs
Labels: UI, DO NOT MERGE YET, LANE ROUTING

#1605 Lane connector incorrectly renders connection lines
  TLM/TLM/UI/SubTools/LaneConnectorTool.cs
Labels: STABLE, LANE ROUTING, Overlays, TEST

#1606 Incorrect segment id for direction calculations
  TLM/TLM/Manager/Impl/ExtSegmentEndManager.cs
Labels: BUG, LANE ROUTING
