Repository CitiesSkylinesMods/TMPE, pull requests merged in 2022-10, with the labels that each got.

#1663 Some Vehicle Restrictions are ignored even with `Strict` Vehicle Aggression setting
  TLM/TLM/Custom/PathFinding/CustomPathManager.cs
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/VehicleRestrictionsManager.cs
  TLM/TLM/Patch/_PathManager/CreatePathPatch.cs
  TLM/TLM/Util/Extensions/VehicleExtensions.cs
Labels: VEHICLE RESTRICTIONS, PATHFINDER

#1626 Parking AI confused in large parking lots
  TLM/Benchmarks/LoopUtilPerfTests.cs
  TLM/Benchmarks/SpiralPerfTests.cs
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtPathManager.cs
  TLM/TLM/Patch/_CitizenAI/_HumanAI/SimulationStepPatch.cs
  TLM/TLM/Util/LoopUtil.cs
  TLM/TLM/Util/Spiral.cs
  TLM/TMPE.UnitTest/Util/LoopUtilTests.cs
  TLM/TMPE.UnitTest/Util/SpiralTests.cs
Labels: PARKING

#1599 `CitizenManager` extension desync when Manager gets patched by other mods
  TLM/TLM/Manager/Impl/AdvancedParkingManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs
  TLM/TLM/Manager/Impl/ExtCitizenManager.cs
  TLM/TLM/Manager/Impl/ExtVehicleManager.cs
  TLM/TLM/Manager/Impl/UtilityManager.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
  TLM/TLM/Patch/_CitizenAI/_HumanAI/ArriveAtDestinationPatch.cs
  TLM/TLM/Patch/_CitizenAI/_HumanAI/SimulationStepPatch.cs
  TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs
  TLM/TLM/Patch/_CitizenAI/_TouristAI/GetVehicleInfoPatch.cs
  TLM/TLM/Patch/_VehicleAI/_CarAI/SimulationStepPatch.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/GetLocalizedStatusPatch.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/ParkVehiclePatch.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/StartPathFindPatch.cs
  TLM/TLM/Patch/_VehicleAI/_PassengerCarAI/UpdateParkedVehiclePatch.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/MainMenu/DebugMenu.cs
  TLM/TLM/UI/RemoveCitizenInstanceButtonExtender.cs
  TLM/TLM/UI/TrafficManagerTool.cs
  TLM/TLM/Util/Extensions/CitizenExtensions.cs
  TLM/TLM/Util/Extensions/CitizenInstanceExtensions.cs
  TLM/TLM/Util/Extensions/CitizenUnitExtensions.cs
  TLM/TMPE.API/Manager/IAdvancedParkingManager.cs
Labels: BUG, confirmed, EXTERNAL, STABLE, technical, performance, TEST

#1661 Parking AI - thinking about a parking spot bugfix
  TLM/TLM/Custom/PathFinding/CustomPathFind.cs
  TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs
Labels: BUG, STABLE, PARKING, PATHFINDER, TEST

#1657 Show DLC icon if the effect of the option depends on DLC availability
  TLM/TLM/State/OptionsTabs/GameplayTab_AIGroups.cs
  TLM/TLM/State/OptionsTabs/GameplayTab_VehicleBehaviourGroup.cs
  TLM/TLM/State/OptionsTabs/PoliciesTab_InEmergenciesGroup.cs
  TLM/TLM/TLM.csproj
  TLM/TLM/UI/Helpers/DLCRestrictedCheckboxOption.cs
Labels: Usability, UI

#1664 What's new 11.7.1.0
  CHANGELOG.md
  TLM/SharedAssemblyInfo.cs
  TLM/TLM/Resources/Translations/JunctionRestrictions.csv
  TLM/TLM/Resources/Translations/LaneRouting.csv
  TLM/TLM/Resources/Translations/Options.csv
  TLM/TLM/Resources/Translations/PrioritySigns.csv
  TLM/TLM/Resources/Translations/SpeedLimits.csv
  TLM/TLM/Resources/Translations/TrafficLights.csv
  TLM/TLM/Resources/Translations/Tutorials.csv
  TLM/TLM/Resources/Translations/VehicleRestrictions.csv
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
  TLM/TLM/Util/VersionUtil.cs
Labels: meta, TEST

#1665 Major bugfix - patch installation
  CHANGELOG.md
  TLM/TLM/Lifecycle/Patcher.cs
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
Labels: BUG, confirmed, Harmony

#1674 11.7.1.1 Stable - changelog update
  CHANGELOG.md
  TLM/TLM/Resources/whats_new.txt
Labels: meta

#1676 Hotfix game crash on load
  CHANGELOG.md
  TLM/TLM/Resources/whats_new.txt
  TLM/TLM/UI/Helpers/CheckboxOption.cs
  TLM/TLM/UI/Helpers/DropDownOption.cs
  TLM/TLM/UI/Helpers/SerializableUIOptionBase.cs
  TLM/TLM/UI/Helpers/SliderOption.cs
  TLM/TLM/UI/WhatsNew/WhatsNew.cs
  TLM/TLM/Util/Shortcuts.cs
Labels: BUG, confirmed, STABLE, UI, TEST

#1670 TTL minor UI improvements.
  TLM/TLM/UI/SubTools/TTL/TimedTrafficLightsTool.cs
Labels: Usability, UI, TRAFFIC LIGHTS

#1673 TTL wait=0 bug
  TLM/TLM/TrafficLight/Impl/TimedTrafficLightsStep.cs
Labels: BUG, TRAFFIC LIGHTS

#1679 bugfix: dead end connection becomes disabled when removed.
  TLM/TLM/Manager/Impl/LaneConnection/ConnectionDataBase.cs
  TLM/TLM/Manager/Impl/LaneConnection/LaneConnectionSubManager.cs
Labels: BUG, high priority, LANE ROUTING
